
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

let url;
try {
  url = env("DB_URL");
} catch (error) {
  url = "mongodb://localhost:27017/ecom-db";
  console.warn("Warning: DB_URL not set in environment variables. Using default local MongoDB URL.");

}

export default defineConfig({
  schema: "prisma/schema/",
  engine: "classic",
  datasource: {
    url
  },
});
