
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model UserAddress
 * 
 */
export type UserAddress = Prisma.UserAddressModel
/**
 * Model CommonAddress
 * 
 */
export type CommonAddress = Prisma.CommonAddressModel
/**
 * Model Advertise
 * 
 */
export type Advertise = Prisma.AdvertiseModel
/**
 * Model Node
 * 
 */
export type Node = Prisma.NodeModel
/**
 * Model Product
 * 
 */
export type Product = Prisma.ProductModel
/**
 * Model Promotion
 * 
 */
export type Promotion = Prisma.PromotionModel
/**
 * Model PromotionType
 * 
 */
export type PromotionType = Prisma.PromotionTypeModel
/**
 * Model Review
 * 
 */
export type Review = Prisma.ReviewModel
/**
 * Model Role
 * 
 */
export type Role = Prisma.RoleModel
/**
 * Model RefreshToken
 * 
 */
export type RefreshToken = Prisma.RefreshTokenModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Variant
 * 
 */
export type Variant = Prisma.VariantModel
