
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const AdvertiseType = {
  BANNER: 'BANNER',
  POPUP: 'POPUP'
} as const

export type AdvertiseType = (typeof AdvertiseType)[keyof typeof AdvertiseType]


export const NodeType = {
  CATEGORY: 'CATEGORY',
  SUBCATEGORY: 'SUBCATEGORY',
  UNIT: 'UNIT',
  BRAND: 'BRAND',
  GST: 'GST'
} as const

export type NodeType = (typeof NodeType)[keyof typeof NodeType]


export const ReviewStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
} as const

export type ReviewStatus = (typeof ReviewStatus)[keyof typeof ReviewStatus]


export const RoleType = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  VENDOR: 'VENDOR'
} as const

export type RoleType = (typeof RoleType)[keyof typeof RoleType]
