
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


export const ModelName = {
  UserAddress: 'UserAddress',
  CommonAddress: 'CommonAddress',
  Advertise: 'Advertise',
  Node: 'Node',
  Product: 'Product',
  Promotion: 'Promotion',
  PromotionType: 'PromotionType',
  Review: 'Review',
  Role: 'Role',
  RefreshToken: 'RefreshToken',
  User: 'User',
  Variant: 'Variant'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const UserAddressScalarFieldEnum = {
  id: 'id',
  commonAddressId: 'commonAddressId',
  streetAddress1: 'streetAddress1',
  streetAddress2: 'streetAddress2',
  landmark: 'landmark',
  isDefault: 'isDefault',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserAddressScalarFieldEnum = (typeof UserAddressScalarFieldEnum)[keyof typeof UserAddressScalarFieldEnum]


export const CommonAddressScalarFieldEnum = {
  id: 'id',
  city: 'city',
  pincode: 'pincode',
  state: 'state',
  createdAt: 'createdAt'
} as const

export type CommonAddressScalarFieldEnum = (typeof CommonAddressScalarFieldEnum)[keyof typeof CommonAddressScalarFieldEnum]


export const AdvertiseScalarFieldEnum = {
  id: 'id',
  title: 'title',
  type: 'type',
  message: 'message',
  videoUrl: 'videoUrl',
  image: 'image',
  redirectUrl: 'redirectUrl',
  isDraft: 'isDraft',
  updatedAt: 'updatedAt',
  createdAt: 'createdAt'
} as const

export type AdvertiseScalarFieldEnum = (typeof AdvertiseScalarFieldEnum)[keyof typeof AdvertiseScalarFieldEnum]


export const NodeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  parentId: 'parentId',
  type: 'type',
  value: 'value'
} as const

export type NodeScalarFieldEnum = (typeof NodeScalarFieldEnum)[keyof typeof NodeScalarFieldEnum]


export const ProductScalarFieldEnum = {
  id: 'id',
  sideImages: 'sideImages',
  thumbnail: 'thumbnail',
  name: 'name',
  description: 'description',
  brandId: 'brandId',
  subCategoryId: 'subCategoryId',
  slug: 'slug',
  sku: 'sku',
  rating: 'rating',
  gstId: 'gstId',
  tags: 'tags',
  features: 'features',
  draft: 'draft',
  upComing: 'upComing',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  nodeId: 'nodeId'
} as const

export type ProductScalarFieldEnum = (typeof ProductScalarFieldEnum)[keyof typeof ProductScalarFieldEnum]


export const PromotionScalarFieldEnum = {
  id: 'id',
  promotionTypeId: 'promotionTypeId',
  description: 'description',
  productId: 'productId',
  validFrom: 'validFrom',
  validTo: 'validTo',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PromotionScalarFieldEnum = (typeof PromotionScalarFieldEnum)[keyof typeof PromotionScalarFieldEnum]


export const PromotionTypeScalarFieldEnum = {
  id: 'id',
  code: 'code',
  value: 'value',
  maxDistance: 'maxDistance',
  minQuantity: 'minQuantity'
} as const

export type PromotionTypeScalarFieldEnum = (typeof PromotionTypeScalarFieldEnum)[keyof typeof PromotionTypeScalarFieldEnum]


export const ReviewScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  userId: 'userId',
  rating: 'rating',
  images: 'images',
  comment: 'comment',
  status: 'status',
  createdAt: 'createdAt'
} as const

export type ReviewScalarFieldEnum = (typeof ReviewScalarFieldEnum)[keyof typeof ReviewScalarFieldEnum]


export const RoleScalarFieldEnum = {
  id: 'id',
  name: 'name'
} as const

export type RoleScalarFieldEnum = (typeof RoleScalarFieldEnum)[keyof typeof RoleScalarFieldEnum]


export const RefreshTokenScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  expiresAt: 'expiresAt'
} as const

export type RefreshTokenScalarFieldEnum = (typeof RefreshTokenScalarFieldEnum)[keyof typeof RefreshTokenScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  phone: 'phone',
  email: 'email',
  firstName: 'firstName',
  lastName: 'lastName',
  dob: 'dob',
  roleId: 'roleId',
  isProfileComplete: 'isProfileComplete',
  lastLogin: 'lastLogin',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const VariantScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  name: 'name',
  unitId: 'unitId',
  magnitude: 'magnitude',
  stock: 'stock',
  price: 'price',
  discount: 'discount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  nodeId: 'nodeId'
} as const

export type VariantScalarFieldEnum = (typeof VariantScalarFieldEnum)[keyof typeof VariantScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]

