
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Advertise` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Advertise
 * 
 */
export type AdvertiseModel = runtime.Types.Result.DefaultSelection<Prisma.$AdvertisePayload>

export type AggregateAdvertise = {
  _count: AdvertiseCountAggregateOutputType | null
  _min: AdvertiseMinAggregateOutputType | null
  _max: AdvertiseMaxAggregateOutputType | null
}

export type AdvertiseMinAggregateOutputType = {
  id: string | null
  title: string | null
  type: $Enums.AdvertiseType | null
  message: string | null
  videoUrl: string | null
  image: string | null
  redirectUrl: string | null
  isDraft: boolean | null
  updatedAt: Date | null
  createdAt: Date | null
}

export type AdvertiseMaxAggregateOutputType = {
  id: string | null
  title: string | null
  type: $Enums.AdvertiseType | null
  message: string | null
  videoUrl: string | null
  image: string | null
  redirectUrl: string | null
  isDraft: boolean | null
  updatedAt: Date | null
  createdAt: Date | null
}

export type AdvertiseCountAggregateOutputType = {
  id: number
  title: number
  type: number
  message: number
  videoUrl: number
  image: number
  redirectUrl: number
  isDraft: number
  updatedAt: number
  createdAt: number
  _all: number
}


export type AdvertiseMinAggregateInputType = {
  id?: true
  title?: true
  type?: true
  message?: true
  videoUrl?: true
  image?: true
  redirectUrl?: true
  isDraft?: true
  updatedAt?: true
  createdAt?: true
}

export type AdvertiseMaxAggregateInputType = {
  id?: true
  title?: true
  type?: true
  message?: true
  videoUrl?: true
  image?: true
  redirectUrl?: true
  isDraft?: true
  updatedAt?: true
  createdAt?: true
}

export type AdvertiseCountAggregateInputType = {
  id?: true
  title?: true
  type?: true
  message?: true
  videoUrl?: true
  image?: true
  redirectUrl?: true
  isDraft?: true
  updatedAt?: true
  createdAt?: true
  _all?: true
}

export type AdvertiseAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Advertise to aggregate.
   */
  where?: Prisma.AdvertiseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Advertises to fetch.
   */
  orderBy?: Prisma.AdvertiseOrderByWithRelationInput | Prisma.AdvertiseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AdvertiseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Advertises from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Advertises.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Advertises
  **/
  _count?: true | AdvertiseCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AdvertiseMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AdvertiseMaxAggregateInputType
}

export type GetAdvertiseAggregateType<T extends AdvertiseAggregateArgs> = {
      [P in keyof T & keyof AggregateAdvertise]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAdvertise[P]>
    : Prisma.GetScalarType<T[P], AggregateAdvertise[P]>
}




export type AdvertiseGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AdvertiseWhereInput
  orderBy?: Prisma.AdvertiseOrderByWithAggregationInput | Prisma.AdvertiseOrderByWithAggregationInput[]
  by: Prisma.AdvertiseScalarFieldEnum[] | Prisma.AdvertiseScalarFieldEnum
  having?: Prisma.AdvertiseScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AdvertiseCountAggregateInputType | true
  _min?: AdvertiseMinAggregateInputType
  _max?: AdvertiseMaxAggregateInputType
}

export type AdvertiseGroupByOutputType = {
  id: string
  title: string
  type: $Enums.AdvertiseType
  message: string | null
  videoUrl: string | null
  image: string | null
  redirectUrl: string | null
  isDraft: boolean
  updatedAt: Date
  createdAt: Date
  _count: AdvertiseCountAggregateOutputType | null
  _min: AdvertiseMinAggregateOutputType | null
  _max: AdvertiseMaxAggregateOutputType | null
}

type GetAdvertiseGroupByPayload<T extends AdvertiseGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AdvertiseGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AdvertiseGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AdvertiseGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AdvertiseGroupByOutputType[P]>
      }
    >
  >



export type AdvertiseWhereInput = {
  AND?: Prisma.AdvertiseWhereInput | Prisma.AdvertiseWhereInput[]
  OR?: Prisma.AdvertiseWhereInput[]
  NOT?: Prisma.AdvertiseWhereInput | Prisma.AdvertiseWhereInput[]
  id?: Prisma.StringFilter<"Advertise"> | string
  title?: Prisma.StringFilter<"Advertise"> | string
  type?: Prisma.EnumAdvertiseTypeFilter<"Advertise"> | $Enums.AdvertiseType
  message?: Prisma.StringNullableFilter<"Advertise"> | string | null
  videoUrl?: Prisma.StringNullableFilter<"Advertise"> | string | null
  image?: Prisma.StringNullableFilter<"Advertise"> | string | null
  redirectUrl?: Prisma.StringNullableFilter<"Advertise"> | string | null
  isDraft?: Prisma.BoolFilter<"Advertise"> | boolean
  updatedAt?: Prisma.DateTimeFilter<"Advertise"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"Advertise"> | Date | string
}

export type AdvertiseOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  type?: Prisma.SortOrder
  message?: Prisma.SortOrder
  videoUrl?: Prisma.SortOrder
  image?: Prisma.SortOrder
  redirectUrl?: Prisma.SortOrder
  isDraft?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AdvertiseWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AdvertiseWhereInput | Prisma.AdvertiseWhereInput[]
  OR?: Prisma.AdvertiseWhereInput[]
  NOT?: Prisma.AdvertiseWhereInput | Prisma.AdvertiseWhereInput[]
  title?: Prisma.StringFilter<"Advertise"> | string
  type?: Prisma.EnumAdvertiseTypeFilter<"Advertise"> | $Enums.AdvertiseType
  message?: Prisma.StringNullableFilter<"Advertise"> | string | null
  videoUrl?: Prisma.StringNullableFilter<"Advertise"> | string | null
  image?: Prisma.StringNullableFilter<"Advertise"> | string | null
  redirectUrl?: Prisma.StringNullableFilter<"Advertise"> | string | null
  isDraft?: Prisma.BoolFilter<"Advertise"> | boolean
  updatedAt?: Prisma.DateTimeFilter<"Advertise"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"Advertise"> | Date | string
}, "id">

export type AdvertiseOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  type?: Prisma.SortOrder
  message?: Prisma.SortOrder
  videoUrl?: Prisma.SortOrder
  image?: Prisma.SortOrder
  redirectUrl?: Prisma.SortOrder
  isDraft?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.AdvertiseCountOrderByAggregateInput
  _max?: Prisma.AdvertiseMaxOrderByAggregateInput
  _min?: Prisma.AdvertiseMinOrderByAggregateInput
}

export type AdvertiseScalarWhereWithAggregatesInput = {
  AND?: Prisma.AdvertiseScalarWhereWithAggregatesInput | Prisma.AdvertiseScalarWhereWithAggregatesInput[]
  OR?: Prisma.AdvertiseScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AdvertiseScalarWhereWithAggregatesInput | Prisma.AdvertiseScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Advertise"> | string
  title?: Prisma.StringWithAggregatesFilter<"Advertise"> | string
  type?: Prisma.EnumAdvertiseTypeWithAggregatesFilter<"Advertise"> | $Enums.AdvertiseType
  message?: Prisma.StringNullableWithAggregatesFilter<"Advertise"> | string | null
  videoUrl?: Prisma.StringNullableWithAggregatesFilter<"Advertise"> | string | null
  image?: Prisma.StringNullableWithAggregatesFilter<"Advertise"> | string | null
  redirectUrl?: Prisma.StringNullableWithAggregatesFilter<"Advertise"> | string | null
  isDraft?: Prisma.BoolWithAggregatesFilter<"Advertise"> | boolean
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Advertise"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Advertise"> | Date | string
}

export type AdvertiseCreateInput = {
  id?: string
  title: string
  type: $Enums.AdvertiseType
  message?: string | null
  videoUrl?: string | null
  image?: string | null
  redirectUrl?: string | null
  isDraft?: boolean
  updatedAt?: Date | string
  createdAt?: Date | string
}

export type AdvertiseUncheckedCreateInput = {
  id?: string
  title: string
  type: $Enums.AdvertiseType
  message?: string | null
  videoUrl?: string | null
  image?: string | null
  redirectUrl?: string | null
  isDraft?: boolean
  updatedAt?: Date | string
  createdAt?: Date | string
}

export type AdvertiseUpdateInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAdvertiseTypeFieldUpdateOperationsInput | $Enums.AdvertiseType
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  videoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redirectUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDraft?: Prisma.BoolFieldUpdateOperationsInput | boolean
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AdvertiseUncheckedUpdateInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAdvertiseTypeFieldUpdateOperationsInput | $Enums.AdvertiseType
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  videoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redirectUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDraft?: Prisma.BoolFieldUpdateOperationsInput | boolean
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AdvertiseCreateManyInput = {
  id?: string
  title: string
  type: $Enums.AdvertiseType
  message?: string | null
  videoUrl?: string | null
  image?: string | null
  redirectUrl?: string | null
  isDraft?: boolean
  updatedAt?: Date | string
  createdAt?: Date | string
}

export type AdvertiseUpdateManyMutationInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAdvertiseTypeFieldUpdateOperationsInput | $Enums.AdvertiseType
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  videoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redirectUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDraft?: Prisma.BoolFieldUpdateOperationsInput | boolean
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AdvertiseUncheckedUpdateManyInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAdvertiseTypeFieldUpdateOperationsInput | $Enums.AdvertiseType
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  videoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redirectUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDraft?: Prisma.BoolFieldUpdateOperationsInput | boolean
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AdvertiseCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  type?: Prisma.SortOrder
  message?: Prisma.SortOrder
  videoUrl?: Prisma.SortOrder
  image?: Prisma.SortOrder
  redirectUrl?: Prisma.SortOrder
  isDraft?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AdvertiseMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  type?: Prisma.SortOrder
  message?: Prisma.SortOrder
  videoUrl?: Prisma.SortOrder
  image?: Prisma.SortOrder
  redirectUrl?: Prisma.SortOrder
  isDraft?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AdvertiseMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  type?: Prisma.SortOrder
  message?: Prisma.SortOrder
  videoUrl?: Prisma.SortOrder
  image?: Prisma.SortOrder
  redirectUrl?: Prisma.SortOrder
  isDraft?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type EnumAdvertiseTypeFieldUpdateOperationsInput = {
  set?: $Enums.AdvertiseType
}



export type AdvertiseSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  type?: boolean
  message?: boolean
  videoUrl?: boolean
  image?: boolean
  redirectUrl?: boolean
  isDraft?: boolean
  updatedAt?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["advertise"]>



export type AdvertiseSelectScalar = {
  id?: boolean
  title?: boolean
  type?: boolean
  message?: boolean
  videoUrl?: boolean
  image?: boolean
  redirectUrl?: boolean
  isDraft?: boolean
  updatedAt?: boolean
  createdAt?: boolean
}

export type AdvertiseOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "type" | "message" | "videoUrl" | "image" | "redirectUrl" | "isDraft" | "updatedAt" | "createdAt", ExtArgs["result"]["advertise"]>

export type $AdvertisePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Advertise"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    type: $Enums.AdvertiseType
    message: string | null
    videoUrl: string | null
    image: string | null
    redirectUrl: string | null
    isDraft: boolean
    updatedAt: Date
    createdAt: Date
  }, ExtArgs["result"]["advertise"]>
  composites: {}
}

export type AdvertiseGetPayload<S extends boolean | null | undefined | AdvertiseDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AdvertisePayload, S>

export type AdvertiseCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AdvertiseFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AdvertiseCountAggregateInputType | true
  }

export interface AdvertiseDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Advertise'], meta: { name: 'Advertise' } }
  /**
   * Find zero or one Advertise that matches the filter.
   * @param {AdvertiseFindUniqueArgs} args - Arguments to find a Advertise
   * @example
   * // Get one Advertise
   * const advertise = await prisma.advertise.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AdvertiseFindUniqueArgs>(args: Prisma.SelectSubset<T, AdvertiseFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AdvertiseClient<runtime.Types.Result.GetResult<Prisma.$AdvertisePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Advertise that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AdvertiseFindUniqueOrThrowArgs} args - Arguments to find a Advertise
   * @example
   * // Get one Advertise
   * const advertise = await prisma.advertise.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AdvertiseFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AdvertiseFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AdvertiseClient<runtime.Types.Result.GetResult<Prisma.$AdvertisePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Advertise that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdvertiseFindFirstArgs} args - Arguments to find a Advertise
   * @example
   * // Get one Advertise
   * const advertise = await prisma.advertise.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AdvertiseFindFirstArgs>(args?: Prisma.SelectSubset<T, AdvertiseFindFirstArgs<ExtArgs>>): Prisma.Prisma__AdvertiseClient<runtime.Types.Result.GetResult<Prisma.$AdvertisePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Advertise that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdvertiseFindFirstOrThrowArgs} args - Arguments to find a Advertise
   * @example
   * // Get one Advertise
   * const advertise = await prisma.advertise.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AdvertiseFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AdvertiseFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AdvertiseClient<runtime.Types.Result.GetResult<Prisma.$AdvertisePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Advertises that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdvertiseFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Advertises
   * const advertises = await prisma.advertise.findMany()
   * 
   * // Get first 10 Advertises
   * const advertises = await prisma.advertise.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const advertiseWithIdOnly = await prisma.advertise.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AdvertiseFindManyArgs>(args?: Prisma.SelectSubset<T, AdvertiseFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AdvertisePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Advertise.
   * @param {AdvertiseCreateArgs} args - Arguments to create a Advertise.
   * @example
   * // Create one Advertise
   * const Advertise = await prisma.advertise.create({
   *   data: {
   *     // ... data to create a Advertise
   *   }
   * })
   * 
   */
  create<T extends AdvertiseCreateArgs>(args: Prisma.SelectSubset<T, AdvertiseCreateArgs<ExtArgs>>): Prisma.Prisma__AdvertiseClient<runtime.Types.Result.GetResult<Prisma.$AdvertisePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Advertises.
   * @param {AdvertiseCreateManyArgs} args - Arguments to create many Advertises.
   * @example
   * // Create many Advertises
   * const advertise = await prisma.advertise.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AdvertiseCreateManyArgs>(args?: Prisma.SelectSubset<T, AdvertiseCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Advertise.
   * @param {AdvertiseDeleteArgs} args - Arguments to delete one Advertise.
   * @example
   * // Delete one Advertise
   * const Advertise = await prisma.advertise.delete({
   *   where: {
   *     // ... filter to delete one Advertise
   *   }
   * })
   * 
   */
  delete<T extends AdvertiseDeleteArgs>(args: Prisma.SelectSubset<T, AdvertiseDeleteArgs<ExtArgs>>): Prisma.Prisma__AdvertiseClient<runtime.Types.Result.GetResult<Prisma.$AdvertisePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Advertise.
   * @param {AdvertiseUpdateArgs} args - Arguments to update one Advertise.
   * @example
   * // Update one Advertise
   * const advertise = await prisma.advertise.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AdvertiseUpdateArgs>(args: Prisma.SelectSubset<T, AdvertiseUpdateArgs<ExtArgs>>): Prisma.Prisma__AdvertiseClient<runtime.Types.Result.GetResult<Prisma.$AdvertisePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Advertises.
   * @param {AdvertiseDeleteManyArgs} args - Arguments to filter Advertises to delete.
   * @example
   * // Delete a few Advertises
   * const { count } = await prisma.advertise.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AdvertiseDeleteManyArgs>(args?: Prisma.SelectSubset<T, AdvertiseDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Advertises.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdvertiseUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Advertises
   * const advertise = await prisma.advertise.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AdvertiseUpdateManyArgs>(args: Prisma.SelectSubset<T, AdvertiseUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Advertise.
   * @param {AdvertiseUpsertArgs} args - Arguments to update or create a Advertise.
   * @example
   * // Update or create a Advertise
   * const advertise = await prisma.advertise.upsert({
   *   create: {
   *     // ... data to create a Advertise
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Advertise we want to update
   *   }
   * })
   */
  upsert<T extends AdvertiseUpsertArgs>(args: Prisma.SelectSubset<T, AdvertiseUpsertArgs<ExtArgs>>): Prisma.Prisma__AdvertiseClient<runtime.Types.Result.GetResult<Prisma.$AdvertisePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Advertises that matches the filter.
   * @param {AdvertiseFindRawArgs} args - Select which filters you would like to apply.
   * @example
   * const advertise = await prisma.advertise.findRaw({
   *   filter: { age: { $gt: 25 } }
   * })
   */
  findRaw(args?: Prisma.AdvertiseFindRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>

  /**
   * Perform aggregation operations on a Advertise.
   * @param {AdvertiseAggregateRawArgs} args - Select which aggregations you would like to apply.
   * @example
   * const advertise = await prisma.advertise.aggregateRaw({
   *   pipeline: [
   *     { $match: { status: "registered" } },
   *     { $group: { _id: "$country", total: { $sum: 1 } } }
   *   ]
   * })
   */
  aggregateRaw(args?: Prisma.AdvertiseAggregateRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>


  /**
   * Count the number of Advertises.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdvertiseCountArgs} args - Arguments to filter Advertises to count.
   * @example
   * // Count the number of Advertises
   * const count = await prisma.advertise.count({
   *   where: {
   *     // ... the filter for the Advertises we want to count
   *   }
   * })
  **/
  count<T extends AdvertiseCountArgs>(
    args?: Prisma.Subset<T, AdvertiseCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AdvertiseCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Advertise.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdvertiseAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AdvertiseAggregateArgs>(args: Prisma.Subset<T, AdvertiseAggregateArgs>): Prisma.PrismaPromise<GetAdvertiseAggregateType<T>>

  /**
   * Group by Advertise.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdvertiseGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AdvertiseGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AdvertiseGroupByArgs['orderBy'] }
      : { orderBy?: AdvertiseGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AdvertiseGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAdvertiseGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Advertise model
 */
readonly fields: AdvertiseFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Advertise.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AdvertiseClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Advertise model
 */
export interface AdvertiseFieldRefs {
  readonly id: Prisma.FieldRef<"Advertise", 'String'>
  readonly title: Prisma.FieldRef<"Advertise", 'String'>
  readonly type: Prisma.FieldRef<"Advertise", 'AdvertiseType'>
  readonly message: Prisma.FieldRef<"Advertise", 'String'>
  readonly videoUrl: Prisma.FieldRef<"Advertise", 'String'>
  readonly image: Prisma.FieldRef<"Advertise", 'String'>
  readonly redirectUrl: Prisma.FieldRef<"Advertise", 'String'>
  readonly isDraft: Prisma.FieldRef<"Advertise", 'Boolean'>
  readonly updatedAt: Prisma.FieldRef<"Advertise", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"Advertise", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Advertise findUnique
 */
export type AdvertiseFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Advertise
   */
  select?: Prisma.AdvertiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Advertise
   */
  omit?: Prisma.AdvertiseOmit<ExtArgs> | null
  /**
   * Filter, which Advertise to fetch.
   */
  where: Prisma.AdvertiseWhereUniqueInput
}

/**
 * Advertise findUniqueOrThrow
 */
export type AdvertiseFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Advertise
   */
  select?: Prisma.AdvertiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Advertise
   */
  omit?: Prisma.AdvertiseOmit<ExtArgs> | null
  /**
   * Filter, which Advertise to fetch.
   */
  where: Prisma.AdvertiseWhereUniqueInput
}

/**
 * Advertise findFirst
 */
export type AdvertiseFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Advertise
   */
  select?: Prisma.AdvertiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Advertise
   */
  omit?: Prisma.AdvertiseOmit<ExtArgs> | null
  /**
   * Filter, which Advertise to fetch.
   */
  where?: Prisma.AdvertiseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Advertises to fetch.
   */
  orderBy?: Prisma.AdvertiseOrderByWithRelationInput | Prisma.AdvertiseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Advertises.
   */
  cursor?: Prisma.AdvertiseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Advertises from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Advertises.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Advertises.
   */
  distinct?: Prisma.AdvertiseScalarFieldEnum | Prisma.AdvertiseScalarFieldEnum[]
}

/**
 * Advertise findFirstOrThrow
 */
export type AdvertiseFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Advertise
   */
  select?: Prisma.AdvertiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Advertise
   */
  omit?: Prisma.AdvertiseOmit<ExtArgs> | null
  /**
   * Filter, which Advertise to fetch.
   */
  where?: Prisma.AdvertiseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Advertises to fetch.
   */
  orderBy?: Prisma.AdvertiseOrderByWithRelationInput | Prisma.AdvertiseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Advertises.
   */
  cursor?: Prisma.AdvertiseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Advertises from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Advertises.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Advertises.
   */
  distinct?: Prisma.AdvertiseScalarFieldEnum | Prisma.AdvertiseScalarFieldEnum[]
}

/**
 * Advertise findMany
 */
export type AdvertiseFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Advertise
   */
  select?: Prisma.AdvertiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Advertise
   */
  omit?: Prisma.AdvertiseOmit<ExtArgs> | null
  /**
   * Filter, which Advertises to fetch.
   */
  where?: Prisma.AdvertiseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Advertises to fetch.
   */
  orderBy?: Prisma.AdvertiseOrderByWithRelationInput | Prisma.AdvertiseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Advertises.
   */
  cursor?: Prisma.AdvertiseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Advertises from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Advertises.
   */
  skip?: number
  distinct?: Prisma.AdvertiseScalarFieldEnum | Prisma.AdvertiseScalarFieldEnum[]
}

/**
 * Advertise create
 */
export type AdvertiseCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Advertise
   */
  select?: Prisma.AdvertiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Advertise
   */
  omit?: Prisma.AdvertiseOmit<ExtArgs> | null
  /**
   * The data needed to create a Advertise.
   */
  data: Prisma.XOR<Prisma.AdvertiseCreateInput, Prisma.AdvertiseUncheckedCreateInput>
}

/**
 * Advertise createMany
 */
export type AdvertiseCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Advertises.
   */
  data: Prisma.AdvertiseCreateManyInput | Prisma.AdvertiseCreateManyInput[]
}

/**
 * Advertise update
 */
export type AdvertiseUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Advertise
   */
  select?: Prisma.AdvertiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Advertise
   */
  omit?: Prisma.AdvertiseOmit<ExtArgs> | null
  /**
   * The data needed to update a Advertise.
   */
  data: Prisma.XOR<Prisma.AdvertiseUpdateInput, Prisma.AdvertiseUncheckedUpdateInput>
  /**
   * Choose, which Advertise to update.
   */
  where: Prisma.AdvertiseWhereUniqueInput
}

/**
 * Advertise updateMany
 */
export type AdvertiseUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Advertises.
   */
  data: Prisma.XOR<Prisma.AdvertiseUpdateManyMutationInput, Prisma.AdvertiseUncheckedUpdateManyInput>
  /**
   * Filter which Advertises to update
   */
  where?: Prisma.AdvertiseWhereInput
  /**
   * Limit how many Advertises to update.
   */
  limit?: number
}

/**
 * Advertise upsert
 */
export type AdvertiseUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Advertise
   */
  select?: Prisma.AdvertiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Advertise
   */
  omit?: Prisma.AdvertiseOmit<ExtArgs> | null
  /**
   * The filter to search for the Advertise to update in case it exists.
   */
  where: Prisma.AdvertiseWhereUniqueInput
  /**
   * In case the Advertise found by the `where` argument doesn't exist, create a new Advertise with this data.
   */
  create: Prisma.XOR<Prisma.AdvertiseCreateInput, Prisma.AdvertiseUncheckedCreateInput>
  /**
   * In case the Advertise was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AdvertiseUpdateInput, Prisma.AdvertiseUncheckedUpdateInput>
}

/**
 * Advertise delete
 */
export type AdvertiseDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Advertise
   */
  select?: Prisma.AdvertiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Advertise
   */
  omit?: Prisma.AdvertiseOmit<ExtArgs> | null
  /**
   * Filter which Advertise to delete.
   */
  where: Prisma.AdvertiseWhereUniqueInput
}

/**
 * Advertise deleteMany
 */
export type AdvertiseDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Advertises to delete
   */
  where?: Prisma.AdvertiseWhereInput
  /**
   * Limit how many Advertises to delete.
   */
  limit?: number
}

/**
 * Advertise findRaw
 */
export type AdvertiseFindRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The query predicate filter. If unspecified, then all documents in the collection will match the predicate. ${@link https://docs.mongodb.com/manual/reference/operator/query MongoDB Docs}.
   */
  filter?: runtime.InputJsonValue
  /**
   * Additional options to pass to the `find` command ${@link https://docs.mongodb.com/manual/reference/command/find/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * Advertise aggregateRaw
 */
export type AdvertiseAggregateRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * An array of aggregation stages to process and transform the document stream via the aggregation pipeline. ${@link https://docs.mongodb.com/manual/reference/operator/aggregation-pipeline MongoDB Docs}.
   */
  pipeline?: runtime.InputJsonValue[]
  /**
   * Additional options to pass to the `aggregate` command ${@link https://docs.mongodb.com/manual/reference/command/aggregate/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * Advertise without action
 */
export type AdvertiseDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Advertise
   */
  select?: Prisma.AdvertiseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Advertise
   */
  omit?: Prisma.AdvertiseOmit<ExtArgs> | null
}
