
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CommonAddress` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model CommonAddress
 * 
 */
export type CommonAddressModel = runtime.Types.Result.DefaultSelection<Prisma.$CommonAddressPayload>

export type AggregateCommonAddress = {
  _count: CommonAddressCountAggregateOutputType | null
  _avg: CommonAddressAvgAggregateOutputType | null
  _sum: CommonAddressSumAggregateOutputType | null
  _min: CommonAddressMinAggregateOutputType | null
  _max: CommonAddressMaxAggregateOutputType | null
}

export type CommonAddressAvgAggregateOutputType = {
  pincode: number | null
}

export type CommonAddressSumAggregateOutputType = {
  pincode: number | null
}

export type CommonAddressMinAggregateOutputType = {
  id: string | null
  city: string | null
  pincode: number | null
  state: string | null
  createdAt: Date | null
}

export type CommonAddressMaxAggregateOutputType = {
  id: string | null
  city: string | null
  pincode: number | null
  state: string | null
  createdAt: Date | null
}

export type CommonAddressCountAggregateOutputType = {
  id: number
  city: number
  pincode: number
  state: number
  createdAt: number
  _all: number
}


export type CommonAddressAvgAggregateInputType = {
  pincode?: true
}

export type CommonAddressSumAggregateInputType = {
  pincode?: true
}

export type CommonAddressMinAggregateInputType = {
  id?: true
  city?: true
  pincode?: true
  state?: true
  createdAt?: true
}

export type CommonAddressMaxAggregateInputType = {
  id?: true
  city?: true
  pincode?: true
  state?: true
  createdAt?: true
}

export type CommonAddressCountAggregateInputType = {
  id?: true
  city?: true
  pincode?: true
  state?: true
  createdAt?: true
  _all?: true
}

export type CommonAddressAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CommonAddress to aggregate.
   */
  where?: Prisma.CommonAddressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CommonAddresses to fetch.
   */
  orderBy?: Prisma.CommonAddressOrderByWithRelationInput | Prisma.CommonAddressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CommonAddressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CommonAddresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CommonAddresses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CommonAddresses
  **/
  _count?: true | CommonAddressCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CommonAddressAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CommonAddressSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CommonAddressMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CommonAddressMaxAggregateInputType
}

export type GetCommonAddressAggregateType<T extends CommonAddressAggregateArgs> = {
      [P in keyof T & keyof AggregateCommonAddress]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCommonAddress[P]>
    : Prisma.GetScalarType<T[P], AggregateCommonAddress[P]>
}




export type CommonAddressGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CommonAddressWhereInput
  orderBy?: Prisma.CommonAddressOrderByWithAggregationInput | Prisma.CommonAddressOrderByWithAggregationInput[]
  by: Prisma.CommonAddressScalarFieldEnum[] | Prisma.CommonAddressScalarFieldEnum
  having?: Prisma.CommonAddressScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CommonAddressCountAggregateInputType | true
  _avg?: CommonAddressAvgAggregateInputType
  _sum?: CommonAddressSumAggregateInputType
  _min?: CommonAddressMinAggregateInputType
  _max?: CommonAddressMaxAggregateInputType
}

export type CommonAddressGroupByOutputType = {
  id: string
  city: string
  pincode: number
  state: string
  createdAt: Date
  _count: CommonAddressCountAggregateOutputType | null
  _avg: CommonAddressAvgAggregateOutputType | null
  _sum: CommonAddressSumAggregateOutputType | null
  _min: CommonAddressMinAggregateOutputType | null
  _max: CommonAddressMaxAggregateOutputType | null
}

type GetCommonAddressGroupByPayload<T extends CommonAddressGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CommonAddressGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CommonAddressGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CommonAddressGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CommonAddressGroupByOutputType[P]>
      }
    >
  >



export type CommonAddressWhereInput = {
  AND?: Prisma.CommonAddressWhereInput | Prisma.CommonAddressWhereInput[]
  OR?: Prisma.CommonAddressWhereInput[]
  NOT?: Prisma.CommonAddressWhereInput | Prisma.CommonAddressWhereInput[]
  id?: Prisma.StringFilter<"CommonAddress"> | string
  city?: Prisma.StringFilter<"CommonAddress"> | string
  pincode?: Prisma.IntFilter<"CommonAddress"> | number
  state?: Prisma.StringFilter<"CommonAddress"> | string
  createdAt?: Prisma.DateTimeFilter<"CommonAddress"> | Date | string
  userAddresses?: Prisma.UserAddressListRelationFilter
}

export type CommonAddressOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  city?: Prisma.SortOrder
  pincode?: Prisma.SortOrder
  state?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  userAddresses?: Prisma.UserAddressOrderByRelationAggregateInput
}

export type CommonAddressWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  state_city_pincode?: Prisma.CommonAddressState_city_pincodeCompoundUniqueInput
  AND?: Prisma.CommonAddressWhereInput | Prisma.CommonAddressWhereInput[]
  OR?: Prisma.CommonAddressWhereInput[]
  NOT?: Prisma.CommonAddressWhereInput | Prisma.CommonAddressWhereInput[]
  city?: Prisma.StringFilter<"CommonAddress"> | string
  pincode?: Prisma.IntFilter<"CommonAddress"> | number
  state?: Prisma.StringFilter<"CommonAddress"> | string
  createdAt?: Prisma.DateTimeFilter<"CommonAddress"> | Date | string
  userAddresses?: Prisma.UserAddressListRelationFilter
}, "id" | "state_city_pincode">

export type CommonAddressOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  city?: Prisma.SortOrder
  pincode?: Prisma.SortOrder
  state?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.CommonAddressCountOrderByAggregateInput
  _avg?: Prisma.CommonAddressAvgOrderByAggregateInput
  _max?: Prisma.CommonAddressMaxOrderByAggregateInput
  _min?: Prisma.CommonAddressMinOrderByAggregateInput
  _sum?: Prisma.CommonAddressSumOrderByAggregateInput
}

export type CommonAddressScalarWhereWithAggregatesInput = {
  AND?: Prisma.CommonAddressScalarWhereWithAggregatesInput | Prisma.CommonAddressScalarWhereWithAggregatesInput[]
  OR?: Prisma.CommonAddressScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CommonAddressScalarWhereWithAggregatesInput | Prisma.CommonAddressScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CommonAddress"> | string
  city?: Prisma.StringWithAggregatesFilter<"CommonAddress"> | string
  pincode?: Prisma.IntWithAggregatesFilter<"CommonAddress"> | number
  state?: Prisma.StringWithAggregatesFilter<"CommonAddress"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CommonAddress"> | Date | string
}

export type CommonAddressCreateInput = {
  id?: string
  city: string
  pincode: number
  state: string
  createdAt?: Date | string
  userAddresses?: Prisma.UserAddressCreateNestedManyWithoutCommonAddressInput
}

export type CommonAddressUncheckedCreateInput = {
  id?: string
  city: string
  pincode: number
  state: string
  createdAt?: Date | string
  userAddresses?: Prisma.UserAddressUncheckedCreateNestedManyWithoutCommonAddressInput
}

export type CommonAddressUpdateInput = {
  city?: Prisma.StringFieldUpdateOperationsInput | string
  pincode?: Prisma.IntFieldUpdateOperationsInput | number
  state?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userAddresses?: Prisma.UserAddressUpdateManyWithoutCommonAddressNestedInput
}

export type CommonAddressUncheckedUpdateInput = {
  city?: Prisma.StringFieldUpdateOperationsInput | string
  pincode?: Prisma.IntFieldUpdateOperationsInput | number
  state?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userAddresses?: Prisma.UserAddressUncheckedUpdateManyWithoutCommonAddressNestedInput
}

export type CommonAddressCreateManyInput = {
  id?: string
  city: string
  pincode: number
  state: string
  createdAt?: Date | string
}

export type CommonAddressUpdateManyMutationInput = {
  city?: Prisma.StringFieldUpdateOperationsInput | string
  pincode?: Prisma.IntFieldUpdateOperationsInput | number
  state?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CommonAddressUncheckedUpdateManyInput = {
  city?: Prisma.StringFieldUpdateOperationsInput | string
  pincode?: Prisma.IntFieldUpdateOperationsInput | number
  state?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CommonAddressScalarRelationFilter = {
  is?: Prisma.CommonAddressWhereInput
  isNot?: Prisma.CommonAddressWhereInput
}

export type CommonAddressState_city_pincodeCompoundUniqueInput = {
  state: string
  city: string
  pincode: number
}

export type CommonAddressCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  city?: Prisma.SortOrder
  pincode?: Prisma.SortOrder
  state?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CommonAddressAvgOrderByAggregateInput = {
  pincode?: Prisma.SortOrder
}

export type CommonAddressMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  city?: Prisma.SortOrder
  pincode?: Prisma.SortOrder
  state?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CommonAddressMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  city?: Prisma.SortOrder
  pincode?: Prisma.SortOrder
  state?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CommonAddressSumOrderByAggregateInput = {
  pincode?: Prisma.SortOrder
}

export type CommonAddressCreateNestedOneWithoutUserAddressesInput = {
  create?: Prisma.XOR<Prisma.CommonAddressCreateWithoutUserAddressesInput, Prisma.CommonAddressUncheckedCreateWithoutUserAddressesInput>
  connectOrCreate?: Prisma.CommonAddressCreateOrConnectWithoutUserAddressesInput
  connect?: Prisma.CommonAddressWhereUniqueInput
}

export type CommonAddressUpdateOneRequiredWithoutUserAddressesNestedInput = {
  create?: Prisma.XOR<Prisma.CommonAddressCreateWithoutUserAddressesInput, Prisma.CommonAddressUncheckedCreateWithoutUserAddressesInput>
  connectOrCreate?: Prisma.CommonAddressCreateOrConnectWithoutUserAddressesInput
  upsert?: Prisma.CommonAddressUpsertWithoutUserAddressesInput
  connect?: Prisma.CommonAddressWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CommonAddressUpdateToOneWithWhereWithoutUserAddressesInput, Prisma.CommonAddressUpdateWithoutUserAddressesInput>, Prisma.CommonAddressUncheckedUpdateWithoutUserAddressesInput>
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type CommonAddressCreateWithoutUserAddressesInput = {
  id?: string
  city: string
  pincode: number
  state: string
  createdAt?: Date | string
}

export type CommonAddressUncheckedCreateWithoutUserAddressesInput = {
  id?: string
  city: string
  pincode: number
  state: string
  createdAt?: Date | string
}

export type CommonAddressCreateOrConnectWithoutUserAddressesInput = {
  where: Prisma.CommonAddressWhereUniqueInput
  create: Prisma.XOR<Prisma.CommonAddressCreateWithoutUserAddressesInput, Prisma.CommonAddressUncheckedCreateWithoutUserAddressesInput>
}

export type CommonAddressUpsertWithoutUserAddressesInput = {
  update: Prisma.XOR<Prisma.CommonAddressUpdateWithoutUserAddressesInput, Prisma.CommonAddressUncheckedUpdateWithoutUserAddressesInput>
  create: Prisma.XOR<Prisma.CommonAddressCreateWithoutUserAddressesInput, Prisma.CommonAddressUncheckedCreateWithoutUserAddressesInput>
  where?: Prisma.CommonAddressWhereInput
}

export type CommonAddressUpdateToOneWithWhereWithoutUserAddressesInput = {
  where?: Prisma.CommonAddressWhereInput
  data: Prisma.XOR<Prisma.CommonAddressUpdateWithoutUserAddressesInput, Prisma.CommonAddressUncheckedUpdateWithoutUserAddressesInput>
}

export type CommonAddressUpdateWithoutUserAddressesInput = {
  city?: Prisma.StringFieldUpdateOperationsInput | string
  pincode?: Prisma.IntFieldUpdateOperationsInput | number
  state?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CommonAddressUncheckedUpdateWithoutUserAddressesInput = {
  city?: Prisma.StringFieldUpdateOperationsInput | string
  pincode?: Prisma.IntFieldUpdateOperationsInput | number
  state?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type CommonAddressCountOutputType
 */

export type CommonAddressCountOutputType = {
  userAddresses: number
}

export type CommonAddressCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  userAddresses?: boolean | CommonAddressCountOutputTypeCountUserAddressesArgs
}

/**
 * CommonAddressCountOutputType without action
 */
export type CommonAddressCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommonAddressCountOutputType
   */
  select?: Prisma.CommonAddressCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CommonAddressCountOutputType without action
 */
export type CommonAddressCountOutputTypeCountUserAddressesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserAddressWhereInput
}


export type CommonAddressSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  city?: boolean
  pincode?: boolean
  state?: boolean
  createdAt?: boolean
  userAddresses?: boolean | Prisma.CommonAddress$userAddressesArgs<ExtArgs>
  _count?: boolean | Prisma.CommonAddressCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["commonAddress"]>



export type CommonAddressSelectScalar = {
  id?: boolean
  city?: boolean
  pincode?: boolean
  state?: boolean
  createdAt?: boolean
}

export type CommonAddressOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "city" | "pincode" | "state" | "createdAt", ExtArgs["result"]["commonAddress"]>
export type CommonAddressInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  userAddresses?: boolean | Prisma.CommonAddress$userAddressesArgs<ExtArgs>
  _count?: boolean | Prisma.CommonAddressCountOutputTypeDefaultArgs<ExtArgs>
}

export type $CommonAddressPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CommonAddress"
  objects: {
    userAddresses: Prisma.$UserAddressPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    city: string
    pincode: number
    state: string
    createdAt: Date
  }, ExtArgs["result"]["commonAddress"]>
  composites: {}
}

export type CommonAddressGetPayload<S extends boolean | null | undefined | CommonAddressDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CommonAddressPayload, S>

export type CommonAddressCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CommonAddressFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CommonAddressCountAggregateInputType | true
  }

export interface CommonAddressDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CommonAddress'], meta: { name: 'CommonAddress' } }
  /**
   * Find zero or one CommonAddress that matches the filter.
   * @param {CommonAddressFindUniqueArgs} args - Arguments to find a CommonAddress
   * @example
   * // Get one CommonAddress
   * const commonAddress = await prisma.commonAddress.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CommonAddressFindUniqueArgs>(args: Prisma.SelectSubset<T, CommonAddressFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CommonAddressClient<runtime.Types.Result.GetResult<Prisma.$CommonAddressPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CommonAddress that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CommonAddressFindUniqueOrThrowArgs} args - Arguments to find a CommonAddress
   * @example
   * // Get one CommonAddress
   * const commonAddress = await prisma.commonAddress.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CommonAddressFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CommonAddressFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CommonAddressClient<runtime.Types.Result.GetResult<Prisma.$CommonAddressPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CommonAddress that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommonAddressFindFirstArgs} args - Arguments to find a CommonAddress
   * @example
   * // Get one CommonAddress
   * const commonAddress = await prisma.commonAddress.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CommonAddressFindFirstArgs>(args?: Prisma.SelectSubset<T, CommonAddressFindFirstArgs<ExtArgs>>): Prisma.Prisma__CommonAddressClient<runtime.Types.Result.GetResult<Prisma.$CommonAddressPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CommonAddress that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommonAddressFindFirstOrThrowArgs} args - Arguments to find a CommonAddress
   * @example
   * // Get one CommonAddress
   * const commonAddress = await prisma.commonAddress.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CommonAddressFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CommonAddressFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CommonAddressClient<runtime.Types.Result.GetResult<Prisma.$CommonAddressPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CommonAddresses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommonAddressFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CommonAddresses
   * const commonAddresses = await prisma.commonAddress.findMany()
   * 
   * // Get first 10 CommonAddresses
   * const commonAddresses = await prisma.commonAddress.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const commonAddressWithIdOnly = await prisma.commonAddress.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CommonAddressFindManyArgs>(args?: Prisma.SelectSubset<T, CommonAddressFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CommonAddressPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CommonAddress.
   * @param {CommonAddressCreateArgs} args - Arguments to create a CommonAddress.
   * @example
   * // Create one CommonAddress
   * const CommonAddress = await prisma.commonAddress.create({
   *   data: {
   *     // ... data to create a CommonAddress
   *   }
   * })
   * 
   */
  create<T extends CommonAddressCreateArgs>(args: Prisma.SelectSubset<T, CommonAddressCreateArgs<ExtArgs>>): Prisma.Prisma__CommonAddressClient<runtime.Types.Result.GetResult<Prisma.$CommonAddressPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CommonAddresses.
   * @param {CommonAddressCreateManyArgs} args - Arguments to create many CommonAddresses.
   * @example
   * // Create many CommonAddresses
   * const commonAddress = await prisma.commonAddress.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CommonAddressCreateManyArgs>(args?: Prisma.SelectSubset<T, CommonAddressCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a CommonAddress.
   * @param {CommonAddressDeleteArgs} args - Arguments to delete one CommonAddress.
   * @example
   * // Delete one CommonAddress
   * const CommonAddress = await prisma.commonAddress.delete({
   *   where: {
   *     // ... filter to delete one CommonAddress
   *   }
   * })
   * 
   */
  delete<T extends CommonAddressDeleteArgs>(args: Prisma.SelectSubset<T, CommonAddressDeleteArgs<ExtArgs>>): Prisma.Prisma__CommonAddressClient<runtime.Types.Result.GetResult<Prisma.$CommonAddressPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CommonAddress.
   * @param {CommonAddressUpdateArgs} args - Arguments to update one CommonAddress.
   * @example
   * // Update one CommonAddress
   * const commonAddress = await prisma.commonAddress.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CommonAddressUpdateArgs>(args: Prisma.SelectSubset<T, CommonAddressUpdateArgs<ExtArgs>>): Prisma.Prisma__CommonAddressClient<runtime.Types.Result.GetResult<Prisma.$CommonAddressPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CommonAddresses.
   * @param {CommonAddressDeleteManyArgs} args - Arguments to filter CommonAddresses to delete.
   * @example
   * // Delete a few CommonAddresses
   * const { count } = await prisma.commonAddress.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CommonAddressDeleteManyArgs>(args?: Prisma.SelectSubset<T, CommonAddressDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CommonAddresses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommonAddressUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CommonAddresses
   * const commonAddress = await prisma.commonAddress.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CommonAddressUpdateManyArgs>(args: Prisma.SelectSubset<T, CommonAddressUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one CommonAddress.
   * @param {CommonAddressUpsertArgs} args - Arguments to update or create a CommonAddress.
   * @example
   * // Update or create a CommonAddress
   * const commonAddress = await prisma.commonAddress.upsert({
   *   create: {
   *     // ... data to create a CommonAddress
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CommonAddress we want to update
   *   }
   * })
   */
  upsert<T extends CommonAddressUpsertArgs>(args: Prisma.SelectSubset<T, CommonAddressUpsertArgs<ExtArgs>>): Prisma.Prisma__CommonAddressClient<runtime.Types.Result.GetResult<Prisma.$CommonAddressPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CommonAddresses that matches the filter.
   * @param {CommonAddressFindRawArgs} args - Select which filters you would like to apply.
   * @example
   * const commonAddress = await prisma.commonAddress.findRaw({
   *   filter: { age: { $gt: 25 } }
   * })
   */
  findRaw(args?: Prisma.CommonAddressFindRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>

  /**
   * Perform aggregation operations on a CommonAddress.
   * @param {CommonAddressAggregateRawArgs} args - Select which aggregations you would like to apply.
   * @example
   * const commonAddress = await prisma.commonAddress.aggregateRaw({
   *   pipeline: [
   *     { $match: { status: "registered" } },
   *     { $group: { _id: "$country", total: { $sum: 1 } } }
   *   ]
   * })
   */
  aggregateRaw(args?: Prisma.CommonAddressAggregateRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>


  /**
   * Count the number of CommonAddresses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommonAddressCountArgs} args - Arguments to filter CommonAddresses to count.
   * @example
   * // Count the number of CommonAddresses
   * const count = await prisma.commonAddress.count({
   *   where: {
   *     // ... the filter for the CommonAddresses we want to count
   *   }
   * })
  **/
  count<T extends CommonAddressCountArgs>(
    args?: Prisma.Subset<T, CommonAddressCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CommonAddressCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CommonAddress.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommonAddressAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CommonAddressAggregateArgs>(args: Prisma.Subset<T, CommonAddressAggregateArgs>): Prisma.PrismaPromise<GetCommonAddressAggregateType<T>>

  /**
   * Group by CommonAddress.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommonAddressGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CommonAddressGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CommonAddressGroupByArgs['orderBy'] }
      : { orderBy?: CommonAddressGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CommonAddressGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCommonAddressGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CommonAddress model
 */
readonly fields: CommonAddressFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CommonAddress.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CommonAddressClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  userAddresses<T extends Prisma.CommonAddress$userAddressesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CommonAddress$userAddressesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserAddressPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CommonAddress model
 */
export interface CommonAddressFieldRefs {
  readonly id: Prisma.FieldRef<"CommonAddress", 'String'>
  readonly city: Prisma.FieldRef<"CommonAddress", 'String'>
  readonly pincode: Prisma.FieldRef<"CommonAddress", 'Int'>
  readonly state: Prisma.FieldRef<"CommonAddress", 'String'>
  readonly createdAt: Prisma.FieldRef<"CommonAddress", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CommonAddress findUnique
 */
export type CommonAddressFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommonAddress
   */
  select?: Prisma.CommonAddressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommonAddress
   */
  omit?: Prisma.CommonAddressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommonAddressInclude<ExtArgs> | null
  /**
   * Filter, which CommonAddress to fetch.
   */
  where: Prisma.CommonAddressWhereUniqueInput
}

/**
 * CommonAddress findUniqueOrThrow
 */
export type CommonAddressFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommonAddress
   */
  select?: Prisma.CommonAddressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommonAddress
   */
  omit?: Prisma.CommonAddressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommonAddressInclude<ExtArgs> | null
  /**
   * Filter, which CommonAddress to fetch.
   */
  where: Prisma.CommonAddressWhereUniqueInput
}

/**
 * CommonAddress findFirst
 */
export type CommonAddressFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommonAddress
   */
  select?: Prisma.CommonAddressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommonAddress
   */
  omit?: Prisma.CommonAddressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommonAddressInclude<ExtArgs> | null
  /**
   * Filter, which CommonAddress to fetch.
   */
  where?: Prisma.CommonAddressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CommonAddresses to fetch.
   */
  orderBy?: Prisma.CommonAddressOrderByWithRelationInput | Prisma.CommonAddressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CommonAddresses.
   */
  cursor?: Prisma.CommonAddressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CommonAddresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CommonAddresses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CommonAddresses.
   */
  distinct?: Prisma.CommonAddressScalarFieldEnum | Prisma.CommonAddressScalarFieldEnum[]
}

/**
 * CommonAddress findFirstOrThrow
 */
export type CommonAddressFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommonAddress
   */
  select?: Prisma.CommonAddressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommonAddress
   */
  omit?: Prisma.CommonAddressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommonAddressInclude<ExtArgs> | null
  /**
   * Filter, which CommonAddress to fetch.
   */
  where?: Prisma.CommonAddressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CommonAddresses to fetch.
   */
  orderBy?: Prisma.CommonAddressOrderByWithRelationInput | Prisma.CommonAddressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CommonAddresses.
   */
  cursor?: Prisma.CommonAddressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CommonAddresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CommonAddresses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CommonAddresses.
   */
  distinct?: Prisma.CommonAddressScalarFieldEnum | Prisma.CommonAddressScalarFieldEnum[]
}

/**
 * CommonAddress findMany
 */
export type CommonAddressFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommonAddress
   */
  select?: Prisma.CommonAddressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommonAddress
   */
  omit?: Prisma.CommonAddressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommonAddressInclude<ExtArgs> | null
  /**
   * Filter, which CommonAddresses to fetch.
   */
  where?: Prisma.CommonAddressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CommonAddresses to fetch.
   */
  orderBy?: Prisma.CommonAddressOrderByWithRelationInput | Prisma.CommonAddressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CommonAddresses.
   */
  cursor?: Prisma.CommonAddressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CommonAddresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CommonAddresses.
   */
  skip?: number
  distinct?: Prisma.CommonAddressScalarFieldEnum | Prisma.CommonAddressScalarFieldEnum[]
}

/**
 * CommonAddress create
 */
export type CommonAddressCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommonAddress
   */
  select?: Prisma.CommonAddressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommonAddress
   */
  omit?: Prisma.CommonAddressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommonAddressInclude<ExtArgs> | null
  /**
   * The data needed to create a CommonAddress.
   */
  data: Prisma.XOR<Prisma.CommonAddressCreateInput, Prisma.CommonAddressUncheckedCreateInput>
}

/**
 * CommonAddress createMany
 */
export type CommonAddressCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CommonAddresses.
   */
  data: Prisma.CommonAddressCreateManyInput | Prisma.CommonAddressCreateManyInput[]
}

/**
 * CommonAddress update
 */
export type CommonAddressUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommonAddress
   */
  select?: Prisma.CommonAddressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommonAddress
   */
  omit?: Prisma.CommonAddressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommonAddressInclude<ExtArgs> | null
  /**
   * The data needed to update a CommonAddress.
   */
  data: Prisma.XOR<Prisma.CommonAddressUpdateInput, Prisma.CommonAddressUncheckedUpdateInput>
  /**
   * Choose, which CommonAddress to update.
   */
  where: Prisma.CommonAddressWhereUniqueInput
}

/**
 * CommonAddress updateMany
 */
export type CommonAddressUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CommonAddresses.
   */
  data: Prisma.XOR<Prisma.CommonAddressUpdateManyMutationInput, Prisma.CommonAddressUncheckedUpdateManyInput>
  /**
   * Filter which CommonAddresses to update
   */
  where?: Prisma.CommonAddressWhereInput
  /**
   * Limit how many CommonAddresses to update.
   */
  limit?: number
}

/**
 * CommonAddress upsert
 */
export type CommonAddressUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommonAddress
   */
  select?: Prisma.CommonAddressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommonAddress
   */
  omit?: Prisma.CommonAddressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommonAddressInclude<ExtArgs> | null
  /**
   * The filter to search for the CommonAddress to update in case it exists.
   */
  where: Prisma.CommonAddressWhereUniqueInput
  /**
   * In case the CommonAddress found by the `where` argument doesn't exist, create a new CommonAddress with this data.
   */
  create: Prisma.XOR<Prisma.CommonAddressCreateInput, Prisma.CommonAddressUncheckedCreateInput>
  /**
   * In case the CommonAddress was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CommonAddressUpdateInput, Prisma.CommonAddressUncheckedUpdateInput>
}

/**
 * CommonAddress delete
 */
export type CommonAddressDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommonAddress
   */
  select?: Prisma.CommonAddressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommonAddress
   */
  omit?: Prisma.CommonAddressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommonAddressInclude<ExtArgs> | null
  /**
   * Filter which CommonAddress to delete.
   */
  where: Prisma.CommonAddressWhereUniqueInput
}

/**
 * CommonAddress deleteMany
 */
export type CommonAddressDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CommonAddresses to delete
   */
  where?: Prisma.CommonAddressWhereInput
  /**
   * Limit how many CommonAddresses to delete.
   */
  limit?: number
}

/**
 * CommonAddress findRaw
 */
export type CommonAddressFindRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The query predicate filter. If unspecified, then all documents in the collection will match the predicate. ${@link https://docs.mongodb.com/manual/reference/operator/query MongoDB Docs}.
   */
  filter?: runtime.InputJsonValue
  /**
   * Additional options to pass to the `find` command ${@link https://docs.mongodb.com/manual/reference/command/find/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * CommonAddress aggregateRaw
 */
export type CommonAddressAggregateRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * An array of aggregation stages to process and transform the document stream via the aggregation pipeline. ${@link https://docs.mongodb.com/manual/reference/operator/aggregation-pipeline MongoDB Docs}.
   */
  pipeline?: runtime.InputJsonValue[]
  /**
   * Additional options to pass to the `aggregate` command ${@link https://docs.mongodb.com/manual/reference/command/aggregate/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * CommonAddress.userAddresses
 */
export type CommonAddress$userAddressesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserAddress
   */
  select?: Prisma.UserAddressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserAddress
   */
  omit?: Prisma.UserAddressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserAddressInclude<ExtArgs> | null
  where?: Prisma.UserAddressWhereInput
  orderBy?: Prisma.UserAddressOrderByWithRelationInput | Prisma.UserAddressOrderByWithRelationInput[]
  cursor?: Prisma.UserAddressWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserAddressScalarFieldEnum | Prisma.UserAddressScalarFieldEnum[]
}

/**
 * CommonAddress without action
 */
export type CommonAddressDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommonAddress
   */
  select?: Prisma.CommonAddressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommonAddress
   */
  omit?: Prisma.CommonAddressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommonAddressInclude<ExtArgs> | null
}
