
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Node` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Node
 * 
 */
export type NodeModel = runtime.Types.Result.DefaultSelection<Prisma.$NodePayload>

export type AggregateNode = {
  _count: NodeCountAggregateOutputType | null
  _avg: NodeAvgAggregateOutputType | null
  _sum: NodeSumAggregateOutputType | null
  _min: NodeMinAggregateOutputType | null
  _max: NodeMaxAggregateOutputType | null
}

export type NodeAvgAggregateOutputType = {
  value: number | null
}

export type NodeSumAggregateOutputType = {
  value: number | null
}

export type NodeMinAggregateOutputType = {
  id: string | null
  name: string | null
  parentId: string | null
  type: $Enums.NodeType | null
  value: number | null
}

export type NodeMaxAggregateOutputType = {
  id: string | null
  name: string | null
  parentId: string | null
  type: $Enums.NodeType | null
  value: number | null
}

export type NodeCountAggregateOutputType = {
  id: number
  name: number
  parentId: number
  type: number
  value: number
  _all: number
}


export type NodeAvgAggregateInputType = {
  value?: true
}

export type NodeSumAggregateInputType = {
  value?: true
}

export type NodeMinAggregateInputType = {
  id?: true
  name?: true
  parentId?: true
  type?: true
  value?: true
}

export type NodeMaxAggregateInputType = {
  id?: true
  name?: true
  parentId?: true
  type?: true
  value?: true
}

export type NodeCountAggregateInputType = {
  id?: true
  name?: true
  parentId?: true
  type?: true
  value?: true
  _all?: true
}

export type NodeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Node to aggregate.
   */
  where?: Prisma.NodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Nodes to fetch.
   */
  orderBy?: Prisma.NodeOrderByWithRelationInput | Prisma.NodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.NodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Nodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Nodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Nodes
  **/
  _count?: true | NodeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: NodeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: NodeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: NodeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: NodeMaxAggregateInputType
}

export type GetNodeAggregateType<T extends NodeAggregateArgs> = {
      [P in keyof T & keyof AggregateNode]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateNode[P]>
    : Prisma.GetScalarType<T[P], AggregateNode[P]>
}




export type NodeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NodeWhereInput
  orderBy?: Prisma.NodeOrderByWithAggregationInput | Prisma.NodeOrderByWithAggregationInput[]
  by: Prisma.NodeScalarFieldEnum[] | Prisma.NodeScalarFieldEnum
  having?: Prisma.NodeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: NodeCountAggregateInputType | true
  _avg?: NodeAvgAggregateInputType
  _sum?: NodeSumAggregateInputType
  _min?: NodeMinAggregateInputType
  _max?: NodeMaxAggregateInputType
}

export type NodeGroupByOutputType = {
  id: string
  name: string | null
  parentId: string | null
  type: $Enums.NodeType
  value: number | null
  _count: NodeCountAggregateOutputType | null
  _avg: NodeAvgAggregateOutputType | null
  _sum: NodeSumAggregateOutputType | null
  _min: NodeMinAggregateOutputType | null
  _max: NodeMaxAggregateOutputType | null
}

type GetNodeGroupByPayload<T extends NodeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<NodeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof NodeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], NodeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], NodeGroupByOutputType[P]>
      }
    >
  >



export type NodeWhereInput = {
  AND?: Prisma.NodeWhereInput | Prisma.NodeWhereInput[]
  OR?: Prisma.NodeWhereInput[]
  NOT?: Prisma.NodeWhereInput | Prisma.NodeWhereInput[]
  id?: Prisma.StringFilter<"Node"> | string
  name?: Prisma.StringNullableFilter<"Node"> | string | null
  parentId?: Prisma.StringNullableFilter<"Node"> | string | null
  type?: Prisma.EnumNodeTypeFilter<"Node"> | $Enums.NodeType
  value?: Prisma.IntNullableFilter<"Node"> | number | null
  ProductsAsCategory?: Prisma.ProductListRelationFilter
  VariantAsUnit?: Prisma.VariantListRelationFilter
  ProductsAsBrand?: Prisma.ProductListRelationFilter
  ProductsAsGst?: Prisma.ProductListRelationFilter
  parent?: Prisma.XOR<Prisma.NodeNullableScalarRelationFilter, Prisma.NodeWhereInput> | null
  children?: Prisma.NodeListRelationFilter
  products?: Prisma.ProductListRelationFilter
  variants?: Prisma.VariantListRelationFilter
}

export type NodeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  parentId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  value?: Prisma.SortOrder
  ProductsAsCategory?: Prisma.ProductOrderByRelationAggregateInput
  VariantAsUnit?: Prisma.VariantOrderByRelationAggregateInput
  ProductsAsBrand?: Prisma.ProductOrderByRelationAggregateInput
  ProductsAsGst?: Prisma.ProductOrderByRelationAggregateInput
  parent?: Prisma.NodeOrderByWithRelationInput
  children?: Prisma.NodeOrderByRelationAggregateInput
  products?: Prisma.ProductOrderByRelationAggregateInput
  variants?: Prisma.VariantOrderByRelationAggregateInput
}

export type NodeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name_type_value?: Prisma.NodeName_type_valueCompoundUniqueInput
  AND?: Prisma.NodeWhereInput | Prisma.NodeWhereInput[]
  OR?: Prisma.NodeWhereInput[]
  NOT?: Prisma.NodeWhereInput | Prisma.NodeWhereInput[]
  name?: Prisma.StringNullableFilter<"Node"> | string | null
  parentId?: Prisma.StringNullableFilter<"Node"> | string | null
  type?: Prisma.EnumNodeTypeFilter<"Node"> | $Enums.NodeType
  value?: Prisma.IntNullableFilter<"Node"> | number | null
  ProductsAsCategory?: Prisma.ProductListRelationFilter
  VariantAsUnit?: Prisma.VariantListRelationFilter
  ProductsAsBrand?: Prisma.ProductListRelationFilter
  ProductsAsGst?: Prisma.ProductListRelationFilter
  parent?: Prisma.XOR<Prisma.NodeNullableScalarRelationFilter, Prisma.NodeWhereInput> | null
  children?: Prisma.NodeListRelationFilter
  products?: Prisma.ProductListRelationFilter
  variants?: Prisma.VariantListRelationFilter
}, "id" | "name_type_value">

export type NodeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  parentId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  value?: Prisma.SortOrder
  _count?: Prisma.NodeCountOrderByAggregateInput
  _avg?: Prisma.NodeAvgOrderByAggregateInput
  _max?: Prisma.NodeMaxOrderByAggregateInput
  _min?: Prisma.NodeMinOrderByAggregateInput
  _sum?: Prisma.NodeSumOrderByAggregateInput
}

export type NodeScalarWhereWithAggregatesInput = {
  AND?: Prisma.NodeScalarWhereWithAggregatesInput | Prisma.NodeScalarWhereWithAggregatesInput[]
  OR?: Prisma.NodeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.NodeScalarWhereWithAggregatesInput | Prisma.NodeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Node"> | string
  name?: Prisma.StringNullableWithAggregatesFilter<"Node"> | string | null
  parentId?: Prisma.StringNullableWithAggregatesFilter<"Node"> | string | null
  type?: Prisma.EnumNodeTypeWithAggregatesFilter<"Node"> | $Enums.NodeType
  value?: Prisma.IntNullableWithAggregatesFilter<"Node"> | number | null
}

export type NodeCreateInput = {
  id?: string
  name?: string | null
  type: $Enums.NodeType
  value?: number | null
  ProductsAsCategory?: Prisma.ProductCreateNestedManyWithoutSubCategoryInput
  VariantAsUnit?: Prisma.VariantCreateNestedManyWithoutUnitInput
  ProductsAsBrand?: Prisma.ProductCreateNestedManyWithoutBrandInput
  ProductsAsGst?: Prisma.ProductCreateNestedManyWithoutGstInput
  parent?: Prisma.NodeCreateNestedOneWithoutChildrenInput
  children?: Prisma.NodeCreateNestedManyWithoutParentInput
  products?: Prisma.ProductCreateNestedManyWithoutNodeInput
  variants?: Prisma.VariantCreateNestedManyWithoutNodeInput
}

export type NodeUncheckedCreateInput = {
  id?: string
  name?: string | null
  parentId?: string | null
  type: $Enums.NodeType
  value?: number | null
  ProductsAsCategory?: Prisma.ProductUncheckedCreateNestedManyWithoutSubCategoryInput
  VariantAsUnit?: Prisma.VariantUncheckedCreateNestedManyWithoutUnitInput
  ProductsAsBrand?: Prisma.ProductUncheckedCreateNestedManyWithoutBrandInput
  ProductsAsGst?: Prisma.ProductUncheckedCreateNestedManyWithoutGstInput
  children?: Prisma.NodeUncheckedCreateNestedManyWithoutParentInput
  products?: Prisma.ProductUncheckedCreateNestedManyWithoutNodeInput
  variants?: Prisma.VariantUncheckedCreateNestedManyWithoutNodeInput
}

export type NodeUpdateInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumNodeTypeFieldUpdateOperationsInput | $Enums.NodeType
  value?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ProductsAsCategory?: Prisma.ProductUpdateManyWithoutSubCategoryNestedInput
  VariantAsUnit?: Prisma.VariantUpdateManyWithoutUnitNestedInput
  ProductsAsBrand?: Prisma.ProductUpdateManyWithoutBrandNestedInput
  ProductsAsGst?: Prisma.ProductUpdateManyWithoutGstNestedInput
  parent?: Prisma.NodeUpdateOneWithoutChildrenNestedInput
  children?: Prisma.NodeUpdateManyWithoutParentNestedInput
  products?: Prisma.ProductUpdateManyWithoutNodeNestedInput
  variants?: Prisma.VariantUpdateManyWithoutNodeNestedInput
}

export type NodeUncheckedUpdateInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumNodeTypeFieldUpdateOperationsInput | $Enums.NodeType
  value?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ProductsAsCategory?: Prisma.ProductUncheckedUpdateManyWithoutSubCategoryNestedInput
  VariantAsUnit?: Prisma.VariantUncheckedUpdateManyWithoutUnitNestedInput
  ProductsAsBrand?: Prisma.ProductUncheckedUpdateManyWithoutBrandNestedInput
  ProductsAsGst?: Prisma.ProductUncheckedUpdateManyWithoutGstNestedInput
  children?: Prisma.NodeUncheckedUpdateManyWithoutParentNestedInput
  products?: Prisma.ProductUncheckedUpdateManyWithoutNodeNestedInput
  variants?: Prisma.VariantUncheckedUpdateManyWithoutNodeNestedInput
}

export type NodeCreateManyInput = {
  id?: string
  name?: string | null
  parentId?: string | null
  type: $Enums.NodeType
  value?: number | null
}

export type NodeUpdateManyMutationInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumNodeTypeFieldUpdateOperationsInput | $Enums.NodeType
  value?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type NodeUncheckedUpdateManyInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumNodeTypeFieldUpdateOperationsInput | $Enums.NodeType
  value?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type NodeNullableScalarRelationFilter = {
  is?: Prisma.NodeWhereInput | null
  isNot?: Prisma.NodeWhereInput | null
}

export type NodeListRelationFilter = {
  every?: Prisma.NodeWhereInput
  some?: Prisma.NodeWhereInput
  none?: Prisma.NodeWhereInput
}

export type NodeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type NodeName_type_valueCompoundUniqueInput = {
  name: string
  type: $Enums.NodeType
  value: number
}

export type NodeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  parentId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  value?: Prisma.SortOrder
}

export type NodeAvgOrderByAggregateInput = {
  value?: Prisma.SortOrder
}

export type NodeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  parentId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  value?: Prisma.SortOrder
}

export type NodeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  parentId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  value?: Prisma.SortOrder
}

export type NodeSumOrderByAggregateInput = {
  value?: Prisma.SortOrder
}

export type NodeScalarRelationFilter = {
  is?: Prisma.NodeWhereInput
  isNot?: Prisma.NodeWhereInput
}

export type NodeCreateNestedOneWithoutChildrenInput = {
  create?: Prisma.XOR<Prisma.NodeCreateWithoutChildrenInput, Prisma.NodeUncheckedCreateWithoutChildrenInput>
  connectOrCreate?: Prisma.NodeCreateOrConnectWithoutChildrenInput
  connect?: Prisma.NodeWhereUniqueInput
}

export type NodeCreateNestedManyWithoutParentInput = {
  create?: Prisma.XOR<Prisma.NodeCreateWithoutParentInput, Prisma.NodeUncheckedCreateWithoutParentInput> | Prisma.NodeCreateWithoutParentInput[] | Prisma.NodeUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.NodeCreateOrConnectWithoutParentInput | Prisma.NodeCreateOrConnectWithoutParentInput[]
  createMany?: Prisma.NodeCreateManyParentInputEnvelope
  connect?: Prisma.NodeWhereUniqueInput | Prisma.NodeWhereUniqueInput[]
}

export type NodeUncheckedCreateNestedManyWithoutParentInput = {
  create?: Prisma.XOR<Prisma.NodeCreateWithoutParentInput, Prisma.NodeUncheckedCreateWithoutParentInput> | Prisma.NodeCreateWithoutParentInput[] | Prisma.NodeUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.NodeCreateOrConnectWithoutParentInput | Prisma.NodeCreateOrConnectWithoutParentInput[]
  createMany?: Prisma.NodeCreateManyParentInputEnvelope
  connect?: Prisma.NodeWhereUniqueInput | Prisma.NodeWhereUniqueInput[]
}

export type EnumNodeTypeFieldUpdateOperationsInput = {
  set?: $Enums.NodeType
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
  unset?: boolean
}

export type NodeUpdateOneWithoutChildrenNestedInput = {
  create?: Prisma.XOR<Prisma.NodeCreateWithoutChildrenInput, Prisma.NodeUncheckedCreateWithoutChildrenInput>
  connectOrCreate?: Prisma.NodeCreateOrConnectWithoutChildrenInput
  upsert?: Prisma.NodeUpsertWithoutChildrenInput
  disconnect?: boolean
  delete?: Prisma.NodeWhereInput | boolean
  connect?: Prisma.NodeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.NodeUpdateToOneWithWhereWithoutChildrenInput, Prisma.NodeUpdateWithoutChildrenInput>, Prisma.NodeUncheckedUpdateWithoutChildrenInput>
}

export type NodeUpdateManyWithoutParentNestedInput = {
  create?: Prisma.XOR<Prisma.NodeCreateWithoutParentInput, Prisma.NodeUncheckedCreateWithoutParentInput> | Prisma.NodeCreateWithoutParentInput[] | Prisma.NodeUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.NodeCreateOrConnectWithoutParentInput | Prisma.NodeCreateOrConnectWithoutParentInput[]
  upsert?: Prisma.NodeUpsertWithWhereUniqueWithoutParentInput | Prisma.NodeUpsertWithWhereUniqueWithoutParentInput[]
  createMany?: Prisma.NodeCreateManyParentInputEnvelope
  set?: Prisma.NodeWhereUniqueInput | Prisma.NodeWhereUniqueInput[]
  disconnect?: Prisma.NodeWhereUniqueInput | Prisma.NodeWhereUniqueInput[]
  delete?: Prisma.NodeWhereUniqueInput | Prisma.NodeWhereUniqueInput[]
  connect?: Prisma.NodeWhereUniqueInput | Prisma.NodeWhereUniqueInput[]
  update?: Prisma.NodeUpdateWithWhereUniqueWithoutParentInput | Prisma.NodeUpdateWithWhereUniqueWithoutParentInput[]
  updateMany?: Prisma.NodeUpdateManyWithWhereWithoutParentInput | Prisma.NodeUpdateManyWithWhereWithoutParentInput[]
  deleteMany?: Prisma.NodeScalarWhereInput | Prisma.NodeScalarWhereInput[]
}

export type NodeUncheckedUpdateManyWithoutParentNestedInput = {
  create?: Prisma.XOR<Prisma.NodeCreateWithoutParentInput, Prisma.NodeUncheckedCreateWithoutParentInput> | Prisma.NodeCreateWithoutParentInput[] | Prisma.NodeUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.NodeCreateOrConnectWithoutParentInput | Prisma.NodeCreateOrConnectWithoutParentInput[]
  upsert?: Prisma.NodeUpsertWithWhereUniqueWithoutParentInput | Prisma.NodeUpsertWithWhereUniqueWithoutParentInput[]
  createMany?: Prisma.NodeCreateManyParentInputEnvelope
  set?: Prisma.NodeWhereUniqueInput | Prisma.NodeWhereUniqueInput[]
  disconnect?: Prisma.NodeWhereUniqueInput | Prisma.NodeWhereUniqueInput[]
  delete?: Prisma.NodeWhereUniqueInput | Prisma.NodeWhereUniqueInput[]
  connect?: Prisma.NodeWhereUniqueInput | Prisma.NodeWhereUniqueInput[]
  update?: Prisma.NodeUpdateWithWhereUniqueWithoutParentInput | Prisma.NodeUpdateWithWhereUniqueWithoutParentInput[]
  updateMany?: Prisma.NodeUpdateManyWithWhereWithoutParentInput | Prisma.NodeUpdateManyWithWhereWithoutParentInput[]
  deleteMany?: Prisma.NodeScalarWhereInput | Prisma.NodeScalarWhereInput[]
}

export type NodeCreateNestedOneWithoutProductsAsBrandInput = {
  create?: Prisma.XOR<Prisma.NodeCreateWithoutProductsAsBrandInput, Prisma.NodeUncheckedCreateWithoutProductsAsBrandInput>
  connectOrCreate?: Prisma.NodeCreateOrConnectWithoutProductsAsBrandInput
  connect?: Prisma.NodeWhereUniqueInput
}

export type NodeCreateNestedOneWithoutProductsAsCategoryInput = {
  create?: Prisma.XOR<Prisma.NodeCreateWithoutProductsAsCategoryInput, Prisma.NodeUncheckedCreateWithoutProductsAsCategoryInput>
  connectOrCreate?: Prisma.NodeCreateOrConnectWithoutProductsAsCategoryInput
  connect?: Prisma.NodeWhereUniqueInput
}

export type NodeCreateNestedOneWithoutProductsAsGstInput = {
  create?: Prisma.XOR<Prisma.NodeCreateWithoutProductsAsGstInput, Prisma.NodeUncheckedCreateWithoutProductsAsGstInput>
  connectOrCreate?: Prisma.NodeCreateOrConnectWithoutProductsAsGstInput
  connect?: Prisma.NodeWhereUniqueInput
}

export type NodeCreateNestedOneWithoutProductsInput = {
  create?: Prisma.XOR<Prisma.NodeCreateWithoutProductsInput, Prisma.NodeUncheckedCreateWithoutProductsInput>
  connectOrCreate?: Prisma.NodeCreateOrConnectWithoutProductsInput
  connect?: Prisma.NodeWhereUniqueInput
}

export type NodeUpdateOneRequiredWithoutProductsAsBrandNestedInput = {
  create?: Prisma.XOR<Prisma.NodeCreateWithoutProductsAsBrandInput, Prisma.NodeUncheckedCreateWithoutProductsAsBrandInput>
  connectOrCreate?: Prisma.NodeCreateOrConnectWithoutProductsAsBrandInput
  upsert?: Prisma.NodeUpsertWithoutProductsAsBrandInput
  connect?: Prisma.NodeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.NodeUpdateToOneWithWhereWithoutProductsAsBrandInput, Prisma.NodeUpdateWithoutProductsAsBrandInput>, Prisma.NodeUncheckedUpdateWithoutProductsAsBrandInput>
}

export type NodeUpdateOneRequiredWithoutProductsAsCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.NodeCreateWithoutProductsAsCategoryInput, Prisma.NodeUncheckedCreateWithoutProductsAsCategoryInput>
  connectOrCreate?: Prisma.NodeCreateOrConnectWithoutProductsAsCategoryInput
  upsert?: Prisma.NodeUpsertWithoutProductsAsCategoryInput
  connect?: Prisma.NodeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.NodeUpdateToOneWithWhereWithoutProductsAsCategoryInput, Prisma.NodeUpdateWithoutProductsAsCategoryInput>, Prisma.NodeUncheckedUpdateWithoutProductsAsCategoryInput>
}

export type NodeUpdateOneRequiredWithoutProductsAsGstNestedInput = {
  create?: Prisma.XOR<Prisma.NodeCreateWithoutProductsAsGstInput, Prisma.NodeUncheckedCreateWithoutProductsAsGstInput>
  connectOrCreate?: Prisma.NodeCreateOrConnectWithoutProductsAsGstInput
  upsert?: Prisma.NodeUpsertWithoutProductsAsGstInput
  connect?: Prisma.NodeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.NodeUpdateToOneWithWhereWithoutProductsAsGstInput, Prisma.NodeUpdateWithoutProductsAsGstInput>, Prisma.NodeUncheckedUpdateWithoutProductsAsGstInput>
}

export type NodeUpdateOneWithoutProductsNestedInput = {
  create?: Prisma.XOR<Prisma.NodeCreateWithoutProductsInput, Prisma.NodeUncheckedCreateWithoutProductsInput>
  connectOrCreate?: Prisma.NodeCreateOrConnectWithoutProductsInput
  upsert?: Prisma.NodeUpsertWithoutProductsInput
  disconnect?: boolean
  delete?: Prisma.NodeWhereInput | boolean
  connect?: Prisma.NodeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.NodeUpdateToOneWithWhereWithoutProductsInput, Prisma.NodeUpdateWithoutProductsInput>, Prisma.NodeUncheckedUpdateWithoutProductsInput>
}

export type NodeCreateNestedOneWithoutVariantAsUnitInput = {
  create?: Prisma.XOR<Prisma.NodeCreateWithoutVariantAsUnitInput, Prisma.NodeUncheckedCreateWithoutVariantAsUnitInput>
  connectOrCreate?: Prisma.NodeCreateOrConnectWithoutVariantAsUnitInput
  connect?: Prisma.NodeWhereUniqueInput
}

export type NodeCreateNestedOneWithoutVariantsInput = {
  create?: Prisma.XOR<Prisma.NodeCreateWithoutVariantsInput, Prisma.NodeUncheckedCreateWithoutVariantsInput>
  connectOrCreate?: Prisma.NodeCreateOrConnectWithoutVariantsInput
  connect?: Prisma.NodeWhereUniqueInput
}

export type NodeUpdateOneRequiredWithoutVariantAsUnitNestedInput = {
  create?: Prisma.XOR<Prisma.NodeCreateWithoutVariantAsUnitInput, Prisma.NodeUncheckedCreateWithoutVariantAsUnitInput>
  connectOrCreate?: Prisma.NodeCreateOrConnectWithoutVariantAsUnitInput
  upsert?: Prisma.NodeUpsertWithoutVariantAsUnitInput
  connect?: Prisma.NodeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.NodeUpdateToOneWithWhereWithoutVariantAsUnitInput, Prisma.NodeUpdateWithoutVariantAsUnitInput>, Prisma.NodeUncheckedUpdateWithoutVariantAsUnitInput>
}

export type NodeUpdateOneWithoutVariantsNestedInput = {
  create?: Prisma.XOR<Prisma.NodeCreateWithoutVariantsInput, Prisma.NodeUncheckedCreateWithoutVariantsInput>
  connectOrCreate?: Prisma.NodeCreateOrConnectWithoutVariantsInput
  upsert?: Prisma.NodeUpsertWithoutVariantsInput
  disconnect?: boolean
  delete?: Prisma.NodeWhereInput | boolean
  connect?: Prisma.NodeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.NodeUpdateToOneWithWhereWithoutVariantsInput, Prisma.NodeUpdateWithoutVariantsInput>, Prisma.NodeUncheckedUpdateWithoutVariantsInput>
}

export type NodeCreateWithoutChildrenInput = {
  id?: string
  name?: string | null
  type: $Enums.NodeType
  value?: number | null
  ProductsAsCategory?: Prisma.ProductCreateNestedManyWithoutSubCategoryInput
  VariantAsUnit?: Prisma.VariantCreateNestedManyWithoutUnitInput
  ProductsAsBrand?: Prisma.ProductCreateNestedManyWithoutBrandInput
  ProductsAsGst?: Prisma.ProductCreateNestedManyWithoutGstInput
  parent?: Prisma.NodeCreateNestedOneWithoutChildrenInput
  products?: Prisma.ProductCreateNestedManyWithoutNodeInput
  variants?: Prisma.VariantCreateNestedManyWithoutNodeInput
}

export type NodeUncheckedCreateWithoutChildrenInput = {
  id?: string
  name?: string | null
  parentId?: string | null
  type: $Enums.NodeType
  value?: number | null
  ProductsAsCategory?: Prisma.ProductUncheckedCreateNestedManyWithoutSubCategoryInput
  VariantAsUnit?: Prisma.VariantUncheckedCreateNestedManyWithoutUnitInput
  ProductsAsBrand?: Prisma.ProductUncheckedCreateNestedManyWithoutBrandInput
  ProductsAsGst?: Prisma.ProductUncheckedCreateNestedManyWithoutGstInput
  products?: Prisma.ProductUncheckedCreateNestedManyWithoutNodeInput
  variants?: Prisma.VariantUncheckedCreateNestedManyWithoutNodeInput
}

export type NodeCreateOrConnectWithoutChildrenInput = {
  where: Prisma.NodeWhereUniqueInput
  create: Prisma.XOR<Prisma.NodeCreateWithoutChildrenInput, Prisma.NodeUncheckedCreateWithoutChildrenInput>
}

export type NodeCreateWithoutParentInput = {
  id?: string
  name?: string | null
  type: $Enums.NodeType
  value?: number | null
  ProductsAsCategory?: Prisma.ProductCreateNestedManyWithoutSubCategoryInput
  VariantAsUnit?: Prisma.VariantCreateNestedManyWithoutUnitInput
  ProductsAsBrand?: Prisma.ProductCreateNestedManyWithoutBrandInput
  ProductsAsGst?: Prisma.ProductCreateNestedManyWithoutGstInput
  children?: Prisma.NodeCreateNestedManyWithoutParentInput
  products?: Prisma.ProductCreateNestedManyWithoutNodeInput
  variants?: Prisma.VariantCreateNestedManyWithoutNodeInput
}

export type NodeUncheckedCreateWithoutParentInput = {
  id?: string
  name?: string | null
  type: $Enums.NodeType
  value?: number | null
  ProductsAsCategory?: Prisma.ProductUncheckedCreateNestedManyWithoutSubCategoryInput
  VariantAsUnit?: Prisma.VariantUncheckedCreateNestedManyWithoutUnitInput
  ProductsAsBrand?: Prisma.ProductUncheckedCreateNestedManyWithoutBrandInput
  ProductsAsGst?: Prisma.ProductUncheckedCreateNestedManyWithoutGstInput
  children?: Prisma.NodeUncheckedCreateNestedManyWithoutParentInput
  products?: Prisma.ProductUncheckedCreateNestedManyWithoutNodeInput
  variants?: Prisma.VariantUncheckedCreateNestedManyWithoutNodeInput
}

export type NodeCreateOrConnectWithoutParentInput = {
  where: Prisma.NodeWhereUniqueInput
  create: Prisma.XOR<Prisma.NodeCreateWithoutParentInput, Prisma.NodeUncheckedCreateWithoutParentInput>
}

export type NodeCreateManyParentInputEnvelope = {
  data: Prisma.NodeCreateManyParentInput | Prisma.NodeCreateManyParentInput[]
}

export type NodeUpsertWithoutChildrenInput = {
  update: Prisma.XOR<Prisma.NodeUpdateWithoutChildrenInput, Prisma.NodeUncheckedUpdateWithoutChildrenInput>
  create: Prisma.XOR<Prisma.NodeCreateWithoutChildrenInput, Prisma.NodeUncheckedCreateWithoutChildrenInput>
  where?: Prisma.NodeWhereInput
}

export type NodeUpdateToOneWithWhereWithoutChildrenInput = {
  where?: Prisma.NodeWhereInput
  data: Prisma.XOR<Prisma.NodeUpdateWithoutChildrenInput, Prisma.NodeUncheckedUpdateWithoutChildrenInput>
}

export type NodeUpdateWithoutChildrenInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumNodeTypeFieldUpdateOperationsInput | $Enums.NodeType
  value?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ProductsAsCategory?: Prisma.ProductUpdateManyWithoutSubCategoryNestedInput
  VariantAsUnit?: Prisma.VariantUpdateManyWithoutUnitNestedInput
  ProductsAsBrand?: Prisma.ProductUpdateManyWithoutBrandNestedInput
  ProductsAsGst?: Prisma.ProductUpdateManyWithoutGstNestedInput
  parent?: Prisma.NodeUpdateOneWithoutChildrenNestedInput
  products?: Prisma.ProductUpdateManyWithoutNodeNestedInput
  variants?: Prisma.VariantUpdateManyWithoutNodeNestedInput
}

export type NodeUncheckedUpdateWithoutChildrenInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumNodeTypeFieldUpdateOperationsInput | $Enums.NodeType
  value?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ProductsAsCategory?: Prisma.ProductUncheckedUpdateManyWithoutSubCategoryNestedInput
  VariantAsUnit?: Prisma.VariantUncheckedUpdateManyWithoutUnitNestedInput
  ProductsAsBrand?: Prisma.ProductUncheckedUpdateManyWithoutBrandNestedInput
  ProductsAsGst?: Prisma.ProductUncheckedUpdateManyWithoutGstNestedInput
  products?: Prisma.ProductUncheckedUpdateManyWithoutNodeNestedInput
  variants?: Prisma.VariantUncheckedUpdateManyWithoutNodeNestedInput
}

export type NodeUpsertWithWhereUniqueWithoutParentInput = {
  where: Prisma.NodeWhereUniqueInput
  update: Prisma.XOR<Prisma.NodeUpdateWithoutParentInput, Prisma.NodeUncheckedUpdateWithoutParentInput>
  create: Prisma.XOR<Prisma.NodeCreateWithoutParentInput, Prisma.NodeUncheckedCreateWithoutParentInput>
}

export type NodeUpdateWithWhereUniqueWithoutParentInput = {
  where: Prisma.NodeWhereUniqueInput
  data: Prisma.XOR<Prisma.NodeUpdateWithoutParentInput, Prisma.NodeUncheckedUpdateWithoutParentInput>
}

export type NodeUpdateManyWithWhereWithoutParentInput = {
  where: Prisma.NodeScalarWhereInput
  data: Prisma.XOR<Prisma.NodeUpdateManyMutationInput, Prisma.NodeUncheckedUpdateManyWithoutParentInput>
}

export type NodeScalarWhereInput = {
  AND?: Prisma.NodeScalarWhereInput | Prisma.NodeScalarWhereInput[]
  OR?: Prisma.NodeScalarWhereInput[]
  NOT?: Prisma.NodeScalarWhereInput | Prisma.NodeScalarWhereInput[]
  id?: Prisma.StringFilter<"Node"> | string
  name?: Prisma.StringNullableFilter<"Node"> | string | null
  parentId?: Prisma.StringNullableFilter<"Node"> | string | null
  type?: Prisma.EnumNodeTypeFilter<"Node"> | $Enums.NodeType
  value?: Prisma.IntNullableFilter<"Node"> | number | null
}

export type NodeCreateWithoutProductsAsBrandInput = {
  id?: string
  name?: string | null
  type: $Enums.NodeType
  value?: number | null
  ProductsAsCategory?: Prisma.ProductCreateNestedManyWithoutSubCategoryInput
  VariantAsUnit?: Prisma.VariantCreateNestedManyWithoutUnitInput
  ProductsAsGst?: Prisma.ProductCreateNestedManyWithoutGstInput
  parent?: Prisma.NodeCreateNestedOneWithoutChildrenInput
  children?: Prisma.NodeCreateNestedManyWithoutParentInput
  products?: Prisma.ProductCreateNestedManyWithoutNodeInput
  variants?: Prisma.VariantCreateNestedManyWithoutNodeInput
}

export type NodeUncheckedCreateWithoutProductsAsBrandInput = {
  id?: string
  name?: string | null
  parentId?: string | null
  type: $Enums.NodeType
  value?: number | null
  ProductsAsCategory?: Prisma.ProductUncheckedCreateNestedManyWithoutSubCategoryInput
  VariantAsUnit?: Prisma.VariantUncheckedCreateNestedManyWithoutUnitInput
  ProductsAsGst?: Prisma.ProductUncheckedCreateNestedManyWithoutGstInput
  children?: Prisma.NodeUncheckedCreateNestedManyWithoutParentInput
  products?: Prisma.ProductUncheckedCreateNestedManyWithoutNodeInput
  variants?: Prisma.VariantUncheckedCreateNestedManyWithoutNodeInput
}

export type NodeCreateOrConnectWithoutProductsAsBrandInput = {
  where: Prisma.NodeWhereUniqueInput
  create: Prisma.XOR<Prisma.NodeCreateWithoutProductsAsBrandInput, Prisma.NodeUncheckedCreateWithoutProductsAsBrandInput>
}

export type NodeCreateWithoutProductsAsCategoryInput = {
  id?: string
  name?: string | null
  type: $Enums.NodeType
  value?: number | null
  VariantAsUnit?: Prisma.VariantCreateNestedManyWithoutUnitInput
  ProductsAsBrand?: Prisma.ProductCreateNestedManyWithoutBrandInput
  ProductsAsGst?: Prisma.ProductCreateNestedManyWithoutGstInput
  parent?: Prisma.NodeCreateNestedOneWithoutChildrenInput
  children?: Prisma.NodeCreateNestedManyWithoutParentInput
  products?: Prisma.ProductCreateNestedManyWithoutNodeInput
  variants?: Prisma.VariantCreateNestedManyWithoutNodeInput
}

export type NodeUncheckedCreateWithoutProductsAsCategoryInput = {
  id?: string
  name?: string | null
  parentId?: string | null
  type: $Enums.NodeType
  value?: number | null
  VariantAsUnit?: Prisma.VariantUncheckedCreateNestedManyWithoutUnitInput
  ProductsAsBrand?: Prisma.ProductUncheckedCreateNestedManyWithoutBrandInput
  ProductsAsGst?: Prisma.ProductUncheckedCreateNestedManyWithoutGstInput
  children?: Prisma.NodeUncheckedCreateNestedManyWithoutParentInput
  products?: Prisma.ProductUncheckedCreateNestedManyWithoutNodeInput
  variants?: Prisma.VariantUncheckedCreateNestedManyWithoutNodeInput
}

export type NodeCreateOrConnectWithoutProductsAsCategoryInput = {
  where: Prisma.NodeWhereUniqueInput
  create: Prisma.XOR<Prisma.NodeCreateWithoutProductsAsCategoryInput, Prisma.NodeUncheckedCreateWithoutProductsAsCategoryInput>
}

export type NodeCreateWithoutProductsAsGstInput = {
  id?: string
  name?: string | null
  type: $Enums.NodeType
  value?: number | null
  ProductsAsCategory?: Prisma.ProductCreateNestedManyWithoutSubCategoryInput
  VariantAsUnit?: Prisma.VariantCreateNestedManyWithoutUnitInput
  ProductsAsBrand?: Prisma.ProductCreateNestedManyWithoutBrandInput
  parent?: Prisma.NodeCreateNestedOneWithoutChildrenInput
  children?: Prisma.NodeCreateNestedManyWithoutParentInput
  products?: Prisma.ProductCreateNestedManyWithoutNodeInput
  variants?: Prisma.VariantCreateNestedManyWithoutNodeInput
}

export type NodeUncheckedCreateWithoutProductsAsGstInput = {
  id?: string
  name?: string | null
  parentId?: string | null
  type: $Enums.NodeType
  value?: number | null
  ProductsAsCategory?: Prisma.ProductUncheckedCreateNestedManyWithoutSubCategoryInput
  VariantAsUnit?: Prisma.VariantUncheckedCreateNestedManyWithoutUnitInput
  ProductsAsBrand?: Prisma.ProductUncheckedCreateNestedManyWithoutBrandInput
  children?: Prisma.NodeUncheckedCreateNestedManyWithoutParentInput
  products?: Prisma.ProductUncheckedCreateNestedManyWithoutNodeInput
  variants?: Prisma.VariantUncheckedCreateNestedManyWithoutNodeInput
}

export type NodeCreateOrConnectWithoutProductsAsGstInput = {
  where: Prisma.NodeWhereUniqueInput
  create: Prisma.XOR<Prisma.NodeCreateWithoutProductsAsGstInput, Prisma.NodeUncheckedCreateWithoutProductsAsGstInput>
}

export type NodeCreateWithoutProductsInput = {
  id?: string
  name?: string | null
  type: $Enums.NodeType
  value?: number | null
  ProductsAsCategory?: Prisma.ProductCreateNestedManyWithoutSubCategoryInput
  VariantAsUnit?: Prisma.VariantCreateNestedManyWithoutUnitInput
  ProductsAsBrand?: Prisma.ProductCreateNestedManyWithoutBrandInput
  ProductsAsGst?: Prisma.ProductCreateNestedManyWithoutGstInput
  parent?: Prisma.NodeCreateNestedOneWithoutChildrenInput
  children?: Prisma.NodeCreateNestedManyWithoutParentInput
  variants?: Prisma.VariantCreateNestedManyWithoutNodeInput
}

export type NodeUncheckedCreateWithoutProductsInput = {
  id?: string
  name?: string | null
  parentId?: string | null
  type: $Enums.NodeType
  value?: number | null
  ProductsAsCategory?: Prisma.ProductUncheckedCreateNestedManyWithoutSubCategoryInput
  VariantAsUnit?: Prisma.VariantUncheckedCreateNestedManyWithoutUnitInput
  ProductsAsBrand?: Prisma.ProductUncheckedCreateNestedManyWithoutBrandInput
  ProductsAsGst?: Prisma.ProductUncheckedCreateNestedManyWithoutGstInput
  children?: Prisma.NodeUncheckedCreateNestedManyWithoutParentInput
  variants?: Prisma.VariantUncheckedCreateNestedManyWithoutNodeInput
}

export type NodeCreateOrConnectWithoutProductsInput = {
  where: Prisma.NodeWhereUniqueInput
  create: Prisma.XOR<Prisma.NodeCreateWithoutProductsInput, Prisma.NodeUncheckedCreateWithoutProductsInput>
}

export type NodeUpsertWithoutProductsAsBrandInput = {
  update: Prisma.XOR<Prisma.NodeUpdateWithoutProductsAsBrandInput, Prisma.NodeUncheckedUpdateWithoutProductsAsBrandInput>
  create: Prisma.XOR<Prisma.NodeCreateWithoutProductsAsBrandInput, Prisma.NodeUncheckedCreateWithoutProductsAsBrandInput>
  where?: Prisma.NodeWhereInput
}

export type NodeUpdateToOneWithWhereWithoutProductsAsBrandInput = {
  where?: Prisma.NodeWhereInput
  data: Prisma.XOR<Prisma.NodeUpdateWithoutProductsAsBrandInput, Prisma.NodeUncheckedUpdateWithoutProductsAsBrandInput>
}

export type NodeUpdateWithoutProductsAsBrandInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumNodeTypeFieldUpdateOperationsInput | $Enums.NodeType
  value?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ProductsAsCategory?: Prisma.ProductUpdateManyWithoutSubCategoryNestedInput
  VariantAsUnit?: Prisma.VariantUpdateManyWithoutUnitNestedInput
  ProductsAsGst?: Prisma.ProductUpdateManyWithoutGstNestedInput
  parent?: Prisma.NodeUpdateOneWithoutChildrenNestedInput
  children?: Prisma.NodeUpdateManyWithoutParentNestedInput
  products?: Prisma.ProductUpdateManyWithoutNodeNestedInput
  variants?: Prisma.VariantUpdateManyWithoutNodeNestedInput
}

export type NodeUncheckedUpdateWithoutProductsAsBrandInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumNodeTypeFieldUpdateOperationsInput | $Enums.NodeType
  value?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ProductsAsCategory?: Prisma.ProductUncheckedUpdateManyWithoutSubCategoryNestedInput
  VariantAsUnit?: Prisma.VariantUncheckedUpdateManyWithoutUnitNestedInput
  ProductsAsGst?: Prisma.ProductUncheckedUpdateManyWithoutGstNestedInput
  children?: Prisma.NodeUncheckedUpdateManyWithoutParentNestedInput
  products?: Prisma.ProductUncheckedUpdateManyWithoutNodeNestedInput
  variants?: Prisma.VariantUncheckedUpdateManyWithoutNodeNestedInput
}

export type NodeUpsertWithoutProductsAsCategoryInput = {
  update: Prisma.XOR<Prisma.NodeUpdateWithoutProductsAsCategoryInput, Prisma.NodeUncheckedUpdateWithoutProductsAsCategoryInput>
  create: Prisma.XOR<Prisma.NodeCreateWithoutProductsAsCategoryInput, Prisma.NodeUncheckedCreateWithoutProductsAsCategoryInput>
  where?: Prisma.NodeWhereInput
}

export type NodeUpdateToOneWithWhereWithoutProductsAsCategoryInput = {
  where?: Prisma.NodeWhereInput
  data: Prisma.XOR<Prisma.NodeUpdateWithoutProductsAsCategoryInput, Prisma.NodeUncheckedUpdateWithoutProductsAsCategoryInput>
}

export type NodeUpdateWithoutProductsAsCategoryInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumNodeTypeFieldUpdateOperationsInput | $Enums.NodeType
  value?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  VariantAsUnit?: Prisma.VariantUpdateManyWithoutUnitNestedInput
  ProductsAsBrand?: Prisma.ProductUpdateManyWithoutBrandNestedInput
  ProductsAsGst?: Prisma.ProductUpdateManyWithoutGstNestedInput
  parent?: Prisma.NodeUpdateOneWithoutChildrenNestedInput
  children?: Prisma.NodeUpdateManyWithoutParentNestedInput
  products?: Prisma.ProductUpdateManyWithoutNodeNestedInput
  variants?: Prisma.VariantUpdateManyWithoutNodeNestedInput
}

export type NodeUncheckedUpdateWithoutProductsAsCategoryInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumNodeTypeFieldUpdateOperationsInput | $Enums.NodeType
  value?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  VariantAsUnit?: Prisma.VariantUncheckedUpdateManyWithoutUnitNestedInput
  ProductsAsBrand?: Prisma.ProductUncheckedUpdateManyWithoutBrandNestedInput
  ProductsAsGst?: Prisma.ProductUncheckedUpdateManyWithoutGstNestedInput
  children?: Prisma.NodeUncheckedUpdateManyWithoutParentNestedInput
  products?: Prisma.ProductUncheckedUpdateManyWithoutNodeNestedInput
  variants?: Prisma.VariantUncheckedUpdateManyWithoutNodeNestedInput
}

export type NodeUpsertWithoutProductsAsGstInput = {
  update: Prisma.XOR<Prisma.NodeUpdateWithoutProductsAsGstInput, Prisma.NodeUncheckedUpdateWithoutProductsAsGstInput>
  create: Prisma.XOR<Prisma.NodeCreateWithoutProductsAsGstInput, Prisma.NodeUncheckedCreateWithoutProductsAsGstInput>
  where?: Prisma.NodeWhereInput
}

export type NodeUpdateToOneWithWhereWithoutProductsAsGstInput = {
  where?: Prisma.NodeWhereInput
  data: Prisma.XOR<Prisma.NodeUpdateWithoutProductsAsGstInput, Prisma.NodeUncheckedUpdateWithoutProductsAsGstInput>
}

export type NodeUpdateWithoutProductsAsGstInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumNodeTypeFieldUpdateOperationsInput | $Enums.NodeType
  value?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ProductsAsCategory?: Prisma.ProductUpdateManyWithoutSubCategoryNestedInput
  VariantAsUnit?: Prisma.VariantUpdateManyWithoutUnitNestedInput
  ProductsAsBrand?: Prisma.ProductUpdateManyWithoutBrandNestedInput
  parent?: Prisma.NodeUpdateOneWithoutChildrenNestedInput
  children?: Prisma.NodeUpdateManyWithoutParentNestedInput
  products?: Prisma.ProductUpdateManyWithoutNodeNestedInput
  variants?: Prisma.VariantUpdateManyWithoutNodeNestedInput
}

export type NodeUncheckedUpdateWithoutProductsAsGstInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumNodeTypeFieldUpdateOperationsInput | $Enums.NodeType
  value?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ProductsAsCategory?: Prisma.ProductUncheckedUpdateManyWithoutSubCategoryNestedInput
  VariantAsUnit?: Prisma.VariantUncheckedUpdateManyWithoutUnitNestedInput
  ProductsAsBrand?: Prisma.ProductUncheckedUpdateManyWithoutBrandNestedInput
  children?: Prisma.NodeUncheckedUpdateManyWithoutParentNestedInput
  products?: Prisma.ProductUncheckedUpdateManyWithoutNodeNestedInput
  variants?: Prisma.VariantUncheckedUpdateManyWithoutNodeNestedInput
}

export type NodeUpsertWithoutProductsInput = {
  update: Prisma.XOR<Prisma.NodeUpdateWithoutProductsInput, Prisma.NodeUncheckedUpdateWithoutProductsInput>
  create: Prisma.XOR<Prisma.NodeCreateWithoutProductsInput, Prisma.NodeUncheckedCreateWithoutProductsInput>
  where?: Prisma.NodeWhereInput
}

export type NodeUpdateToOneWithWhereWithoutProductsInput = {
  where?: Prisma.NodeWhereInput
  data: Prisma.XOR<Prisma.NodeUpdateWithoutProductsInput, Prisma.NodeUncheckedUpdateWithoutProductsInput>
}

export type NodeUpdateWithoutProductsInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumNodeTypeFieldUpdateOperationsInput | $Enums.NodeType
  value?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ProductsAsCategory?: Prisma.ProductUpdateManyWithoutSubCategoryNestedInput
  VariantAsUnit?: Prisma.VariantUpdateManyWithoutUnitNestedInput
  ProductsAsBrand?: Prisma.ProductUpdateManyWithoutBrandNestedInput
  ProductsAsGst?: Prisma.ProductUpdateManyWithoutGstNestedInput
  parent?: Prisma.NodeUpdateOneWithoutChildrenNestedInput
  children?: Prisma.NodeUpdateManyWithoutParentNestedInput
  variants?: Prisma.VariantUpdateManyWithoutNodeNestedInput
}

export type NodeUncheckedUpdateWithoutProductsInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumNodeTypeFieldUpdateOperationsInput | $Enums.NodeType
  value?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ProductsAsCategory?: Prisma.ProductUncheckedUpdateManyWithoutSubCategoryNestedInput
  VariantAsUnit?: Prisma.VariantUncheckedUpdateManyWithoutUnitNestedInput
  ProductsAsBrand?: Prisma.ProductUncheckedUpdateManyWithoutBrandNestedInput
  ProductsAsGst?: Prisma.ProductUncheckedUpdateManyWithoutGstNestedInput
  children?: Prisma.NodeUncheckedUpdateManyWithoutParentNestedInput
  variants?: Prisma.VariantUncheckedUpdateManyWithoutNodeNestedInput
}

export type NodeCreateWithoutVariantAsUnitInput = {
  id?: string
  name?: string | null
  type: $Enums.NodeType
  value?: number | null
  ProductsAsCategory?: Prisma.ProductCreateNestedManyWithoutSubCategoryInput
  ProductsAsBrand?: Prisma.ProductCreateNestedManyWithoutBrandInput
  ProductsAsGst?: Prisma.ProductCreateNestedManyWithoutGstInput
  parent?: Prisma.NodeCreateNestedOneWithoutChildrenInput
  children?: Prisma.NodeCreateNestedManyWithoutParentInput
  products?: Prisma.ProductCreateNestedManyWithoutNodeInput
  variants?: Prisma.VariantCreateNestedManyWithoutNodeInput
}

export type NodeUncheckedCreateWithoutVariantAsUnitInput = {
  id?: string
  name?: string | null
  parentId?: string | null
  type: $Enums.NodeType
  value?: number | null
  ProductsAsCategory?: Prisma.ProductUncheckedCreateNestedManyWithoutSubCategoryInput
  ProductsAsBrand?: Prisma.ProductUncheckedCreateNestedManyWithoutBrandInput
  ProductsAsGst?: Prisma.ProductUncheckedCreateNestedManyWithoutGstInput
  children?: Prisma.NodeUncheckedCreateNestedManyWithoutParentInput
  products?: Prisma.ProductUncheckedCreateNestedManyWithoutNodeInput
  variants?: Prisma.VariantUncheckedCreateNestedManyWithoutNodeInput
}

export type NodeCreateOrConnectWithoutVariantAsUnitInput = {
  where: Prisma.NodeWhereUniqueInput
  create: Prisma.XOR<Prisma.NodeCreateWithoutVariantAsUnitInput, Prisma.NodeUncheckedCreateWithoutVariantAsUnitInput>
}

export type NodeCreateWithoutVariantsInput = {
  id?: string
  name?: string | null
  type: $Enums.NodeType
  value?: number | null
  ProductsAsCategory?: Prisma.ProductCreateNestedManyWithoutSubCategoryInput
  VariantAsUnit?: Prisma.VariantCreateNestedManyWithoutUnitInput
  ProductsAsBrand?: Prisma.ProductCreateNestedManyWithoutBrandInput
  ProductsAsGst?: Prisma.ProductCreateNestedManyWithoutGstInput
  parent?: Prisma.NodeCreateNestedOneWithoutChildrenInput
  children?: Prisma.NodeCreateNestedManyWithoutParentInput
  products?: Prisma.ProductCreateNestedManyWithoutNodeInput
}

export type NodeUncheckedCreateWithoutVariantsInput = {
  id?: string
  name?: string | null
  parentId?: string | null
  type: $Enums.NodeType
  value?: number | null
  ProductsAsCategory?: Prisma.ProductUncheckedCreateNestedManyWithoutSubCategoryInput
  VariantAsUnit?: Prisma.VariantUncheckedCreateNestedManyWithoutUnitInput
  ProductsAsBrand?: Prisma.ProductUncheckedCreateNestedManyWithoutBrandInput
  ProductsAsGst?: Prisma.ProductUncheckedCreateNestedManyWithoutGstInput
  children?: Prisma.NodeUncheckedCreateNestedManyWithoutParentInput
  products?: Prisma.ProductUncheckedCreateNestedManyWithoutNodeInput
}

export type NodeCreateOrConnectWithoutVariantsInput = {
  where: Prisma.NodeWhereUniqueInput
  create: Prisma.XOR<Prisma.NodeCreateWithoutVariantsInput, Prisma.NodeUncheckedCreateWithoutVariantsInput>
}

export type NodeUpsertWithoutVariantAsUnitInput = {
  update: Prisma.XOR<Prisma.NodeUpdateWithoutVariantAsUnitInput, Prisma.NodeUncheckedUpdateWithoutVariantAsUnitInput>
  create: Prisma.XOR<Prisma.NodeCreateWithoutVariantAsUnitInput, Prisma.NodeUncheckedCreateWithoutVariantAsUnitInput>
  where?: Prisma.NodeWhereInput
}

export type NodeUpdateToOneWithWhereWithoutVariantAsUnitInput = {
  where?: Prisma.NodeWhereInput
  data: Prisma.XOR<Prisma.NodeUpdateWithoutVariantAsUnitInput, Prisma.NodeUncheckedUpdateWithoutVariantAsUnitInput>
}

export type NodeUpdateWithoutVariantAsUnitInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumNodeTypeFieldUpdateOperationsInput | $Enums.NodeType
  value?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ProductsAsCategory?: Prisma.ProductUpdateManyWithoutSubCategoryNestedInput
  ProductsAsBrand?: Prisma.ProductUpdateManyWithoutBrandNestedInput
  ProductsAsGst?: Prisma.ProductUpdateManyWithoutGstNestedInput
  parent?: Prisma.NodeUpdateOneWithoutChildrenNestedInput
  children?: Prisma.NodeUpdateManyWithoutParentNestedInput
  products?: Prisma.ProductUpdateManyWithoutNodeNestedInput
  variants?: Prisma.VariantUpdateManyWithoutNodeNestedInput
}

export type NodeUncheckedUpdateWithoutVariantAsUnitInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumNodeTypeFieldUpdateOperationsInput | $Enums.NodeType
  value?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ProductsAsCategory?: Prisma.ProductUncheckedUpdateManyWithoutSubCategoryNestedInput
  ProductsAsBrand?: Prisma.ProductUncheckedUpdateManyWithoutBrandNestedInput
  ProductsAsGst?: Prisma.ProductUncheckedUpdateManyWithoutGstNestedInput
  children?: Prisma.NodeUncheckedUpdateManyWithoutParentNestedInput
  products?: Prisma.ProductUncheckedUpdateManyWithoutNodeNestedInput
  variants?: Prisma.VariantUncheckedUpdateManyWithoutNodeNestedInput
}

export type NodeUpsertWithoutVariantsInput = {
  update: Prisma.XOR<Prisma.NodeUpdateWithoutVariantsInput, Prisma.NodeUncheckedUpdateWithoutVariantsInput>
  create: Prisma.XOR<Prisma.NodeCreateWithoutVariantsInput, Prisma.NodeUncheckedCreateWithoutVariantsInput>
  where?: Prisma.NodeWhereInput
}

export type NodeUpdateToOneWithWhereWithoutVariantsInput = {
  where?: Prisma.NodeWhereInput
  data: Prisma.XOR<Prisma.NodeUpdateWithoutVariantsInput, Prisma.NodeUncheckedUpdateWithoutVariantsInput>
}

export type NodeUpdateWithoutVariantsInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumNodeTypeFieldUpdateOperationsInput | $Enums.NodeType
  value?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ProductsAsCategory?: Prisma.ProductUpdateManyWithoutSubCategoryNestedInput
  VariantAsUnit?: Prisma.VariantUpdateManyWithoutUnitNestedInput
  ProductsAsBrand?: Prisma.ProductUpdateManyWithoutBrandNestedInput
  ProductsAsGst?: Prisma.ProductUpdateManyWithoutGstNestedInput
  parent?: Prisma.NodeUpdateOneWithoutChildrenNestedInput
  children?: Prisma.NodeUpdateManyWithoutParentNestedInput
  products?: Prisma.ProductUpdateManyWithoutNodeNestedInput
}

export type NodeUncheckedUpdateWithoutVariantsInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumNodeTypeFieldUpdateOperationsInput | $Enums.NodeType
  value?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ProductsAsCategory?: Prisma.ProductUncheckedUpdateManyWithoutSubCategoryNestedInput
  VariantAsUnit?: Prisma.VariantUncheckedUpdateManyWithoutUnitNestedInput
  ProductsAsBrand?: Prisma.ProductUncheckedUpdateManyWithoutBrandNestedInput
  ProductsAsGst?: Prisma.ProductUncheckedUpdateManyWithoutGstNestedInput
  children?: Prisma.NodeUncheckedUpdateManyWithoutParentNestedInput
  products?: Prisma.ProductUncheckedUpdateManyWithoutNodeNestedInput
}

export type NodeCreateManyParentInput = {
  id?: string
  name?: string | null
  type: $Enums.NodeType
  value?: number | null
}

export type NodeUpdateWithoutParentInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumNodeTypeFieldUpdateOperationsInput | $Enums.NodeType
  value?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ProductsAsCategory?: Prisma.ProductUpdateManyWithoutSubCategoryNestedInput
  VariantAsUnit?: Prisma.VariantUpdateManyWithoutUnitNestedInput
  ProductsAsBrand?: Prisma.ProductUpdateManyWithoutBrandNestedInput
  ProductsAsGst?: Prisma.ProductUpdateManyWithoutGstNestedInput
  children?: Prisma.NodeUpdateManyWithoutParentNestedInput
  products?: Prisma.ProductUpdateManyWithoutNodeNestedInput
  variants?: Prisma.VariantUpdateManyWithoutNodeNestedInput
}

export type NodeUncheckedUpdateWithoutParentInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumNodeTypeFieldUpdateOperationsInput | $Enums.NodeType
  value?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ProductsAsCategory?: Prisma.ProductUncheckedUpdateManyWithoutSubCategoryNestedInput
  VariantAsUnit?: Prisma.VariantUncheckedUpdateManyWithoutUnitNestedInput
  ProductsAsBrand?: Prisma.ProductUncheckedUpdateManyWithoutBrandNestedInput
  ProductsAsGst?: Prisma.ProductUncheckedUpdateManyWithoutGstNestedInput
  children?: Prisma.NodeUncheckedUpdateManyWithoutParentNestedInput
  products?: Prisma.ProductUncheckedUpdateManyWithoutNodeNestedInput
  variants?: Prisma.VariantUncheckedUpdateManyWithoutNodeNestedInput
}

export type NodeUncheckedUpdateManyWithoutParentInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumNodeTypeFieldUpdateOperationsInput | $Enums.NodeType
  value?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}


/**
 * Count Type NodeCountOutputType
 */

export type NodeCountOutputType = {
  ProductsAsCategory: number
  VariantAsUnit: number
  ProductsAsBrand: number
  ProductsAsGst: number
  children: number
  products: number
  variants: number
}

export type NodeCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ProductsAsCategory?: boolean | NodeCountOutputTypeCountProductsAsCategoryArgs
  VariantAsUnit?: boolean | NodeCountOutputTypeCountVariantAsUnitArgs
  ProductsAsBrand?: boolean | NodeCountOutputTypeCountProductsAsBrandArgs
  ProductsAsGst?: boolean | NodeCountOutputTypeCountProductsAsGstArgs
  children?: boolean | NodeCountOutputTypeCountChildrenArgs
  products?: boolean | NodeCountOutputTypeCountProductsArgs
  variants?: boolean | NodeCountOutputTypeCountVariantsArgs
}

/**
 * NodeCountOutputType without action
 */
export type NodeCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NodeCountOutputType
   */
  select?: Prisma.NodeCountOutputTypeSelect<ExtArgs> | null
}

/**
 * NodeCountOutputType without action
 */
export type NodeCountOutputTypeCountProductsAsCategoryArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductWhereInput
}

/**
 * NodeCountOutputType without action
 */
export type NodeCountOutputTypeCountVariantAsUnitArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VariantWhereInput
}

/**
 * NodeCountOutputType without action
 */
export type NodeCountOutputTypeCountProductsAsBrandArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductWhereInput
}

/**
 * NodeCountOutputType without action
 */
export type NodeCountOutputTypeCountProductsAsGstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductWhereInput
}

/**
 * NodeCountOutputType without action
 */
export type NodeCountOutputTypeCountChildrenArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NodeWhereInput
}

/**
 * NodeCountOutputType without action
 */
export type NodeCountOutputTypeCountProductsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductWhereInput
}

/**
 * NodeCountOutputType without action
 */
export type NodeCountOutputTypeCountVariantsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VariantWhereInput
}


export type NodeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  parentId?: boolean
  type?: boolean
  value?: boolean
  ProductsAsCategory?: boolean | Prisma.Node$ProductsAsCategoryArgs<ExtArgs>
  VariantAsUnit?: boolean | Prisma.Node$VariantAsUnitArgs<ExtArgs>
  ProductsAsBrand?: boolean | Prisma.Node$ProductsAsBrandArgs<ExtArgs>
  ProductsAsGst?: boolean | Prisma.Node$ProductsAsGstArgs<ExtArgs>
  parent?: boolean | Prisma.Node$parentArgs<ExtArgs>
  children?: boolean | Prisma.Node$childrenArgs<ExtArgs>
  products?: boolean | Prisma.Node$productsArgs<ExtArgs>
  variants?: boolean | Prisma.Node$variantsArgs<ExtArgs>
  _count?: boolean | Prisma.NodeCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["node"]>



export type NodeSelectScalar = {
  id?: boolean
  name?: boolean
  parentId?: boolean
  type?: boolean
  value?: boolean
}

export type NodeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "parentId" | "type" | "value", ExtArgs["result"]["node"]>
export type NodeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ProductsAsCategory?: boolean | Prisma.Node$ProductsAsCategoryArgs<ExtArgs>
  VariantAsUnit?: boolean | Prisma.Node$VariantAsUnitArgs<ExtArgs>
  ProductsAsBrand?: boolean | Prisma.Node$ProductsAsBrandArgs<ExtArgs>
  ProductsAsGst?: boolean | Prisma.Node$ProductsAsGstArgs<ExtArgs>
  parent?: boolean | Prisma.Node$parentArgs<ExtArgs>
  children?: boolean | Prisma.Node$childrenArgs<ExtArgs>
  products?: boolean | Prisma.Node$productsArgs<ExtArgs>
  variants?: boolean | Prisma.Node$variantsArgs<ExtArgs>
  _count?: boolean | Prisma.NodeCountOutputTypeDefaultArgs<ExtArgs>
}

export type $NodePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Node"
  objects: {
    ProductsAsCategory: Prisma.$ProductPayload<ExtArgs>[]
    VariantAsUnit: Prisma.$VariantPayload<ExtArgs>[]
    ProductsAsBrand: Prisma.$ProductPayload<ExtArgs>[]
    ProductsAsGst: Prisma.$ProductPayload<ExtArgs>[]
    parent: Prisma.$NodePayload<ExtArgs> | null
    children: Prisma.$NodePayload<ExtArgs>[]
    products: Prisma.$ProductPayload<ExtArgs>[]
    variants: Prisma.$VariantPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string | null
    parentId: string | null
    type: $Enums.NodeType
    value: number | null
  }, ExtArgs["result"]["node"]>
  composites: {}
}

export type NodeGetPayload<S extends boolean | null | undefined | NodeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$NodePayload, S>

export type NodeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<NodeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: NodeCountAggregateInputType | true
  }

export interface NodeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Node'], meta: { name: 'Node' } }
  /**
   * Find zero or one Node that matches the filter.
   * @param {NodeFindUniqueArgs} args - Arguments to find a Node
   * @example
   * // Get one Node
   * const node = await prisma.node.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends NodeFindUniqueArgs>(args: Prisma.SelectSubset<T, NodeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__NodeClient<runtime.Types.Result.GetResult<Prisma.$NodePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Node that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {NodeFindUniqueOrThrowArgs} args - Arguments to find a Node
   * @example
   * // Get one Node
   * const node = await prisma.node.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends NodeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, NodeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__NodeClient<runtime.Types.Result.GetResult<Prisma.$NodePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Node that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NodeFindFirstArgs} args - Arguments to find a Node
   * @example
   * // Get one Node
   * const node = await prisma.node.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends NodeFindFirstArgs>(args?: Prisma.SelectSubset<T, NodeFindFirstArgs<ExtArgs>>): Prisma.Prisma__NodeClient<runtime.Types.Result.GetResult<Prisma.$NodePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Node that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NodeFindFirstOrThrowArgs} args - Arguments to find a Node
   * @example
   * // Get one Node
   * const node = await prisma.node.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends NodeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, NodeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__NodeClient<runtime.Types.Result.GetResult<Prisma.$NodePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Nodes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NodeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Nodes
   * const nodes = await prisma.node.findMany()
   * 
   * // Get first 10 Nodes
   * const nodes = await prisma.node.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const nodeWithIdOnly = await prisma.node.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends NodeFindManyArgs>(args?: Prisma.SelectSubset<T, NodeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NodePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Node.
   * @param {NodeCreateArgs} args - Arguments to create a Node.
   * @example
   * // Create one Node
   * const Node = await prisma.node.create({
   *   data: {
   *     // ... data to create a Node
   *   }
   * })
   * 
   */
  create<T extends NodeCreateArgs>(args: Prisma.SelectSubset<T, NodeCreateArgs<ExtArgs>>): Prisma.Prisma__NodeClient<runtime.Types.Result.GetResult<Prisma.$NodePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Nodes.
   * @param {NodeCreateManyArgs} args - Arguments to create many Nodes.
   * @example
   * // Create many Nodes
   * const node = await prisma.node.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends NodeCreateManyArgs>(args?: Prisma.SelectSubset<T, NodeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Node.
   * @param {NodeDeleteArgs} args - Arguments to delete one Node.
   * @example
   * // Delete one Node
   * const Node = await prisma.node.delete({
   *   where: {
   *     // ... filter to delete one Node
   *   }
   * })
   * 
   */
  delete<T extends NodeDeleteArgs>(args: Prisma.SelectSubset<T, NodeDeleteArgs<ExtArgs>>): Prisma.Prisma__NodeClient<runtime.Types.Result.GetResult<Prisma.$NodePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Node.
   * @param {NodeUpdateArgs} args - Arguments to update one Node.
   * @example
   * // Update one Node
   * const node = await prisma.node.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends NodeUpdateArgs>(args: Prisma.SelectSubset<T, NodeUpdateArgs<ExtArgs>>): Prisma.Prisma__NodeClient<runtime.Types.Result.GetResult<Prisma.$NodePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Nodes.
   * @param {NodeDeleteManyArgs} args - Arguments to filter Nodes to delete.
   * @example
   * // Delete a few Nodes
   * const { count } = await prisma.node.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends NodeDeleteManyArgs>(args?: Prisma.SelectSubset<T, NodeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Nodes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NodeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Nodes
   * const node = await prisma.node.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends NodeUpdateManyArgs>(args: Prisma.SelectSubset<T, NodeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Node.
   * @param {NodeUpsertArgs} args - Arguments to update or create a Node.
   * @example
   * // Update or create a Node
   * const node = await prisma.node.upsert({
   *   create: {
   *     // ... data to create a Node
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Node we want to update
   *   }
   * })
   */
  upsert<T extends NodeUpsertArgs>(args: Prisma.SelectSubset<T, NodeUpsertArgs<ExtArgs>>): Prisma.Prisma__NodeClient<runtime.Types.Result.GetResult<Prisma.$NodePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Nodes that matches the filter.
   * @param {NodeFindRawArgs} args - Select which filters you would like to apply.
   * @example
   * const node = await prisma.node.findRaw({
   *   filter: { age: { $gt: 25 } }
   * })
   */
  findRaw(args?: Prisma.NodeFindRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>

  /**
   * Perform aggregation operations on a Node.
   * @param {NodeAggregateRawArgs} args - Select which aggregations you would like to apply.
   * @example
   * const node = await prisma.node.aggregateRaw({
   *   pipeline: [
   *     { $match: { status: "registered" } },
   *     { $group: { _id: "$country", total: { $sum: 1 } } }
   *   ]
   * })
   */
  aggregateRaw(args?: Prisma.NodeAggregateRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>


  /**
   * Count the number of Nodes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NodeCountArgs} args - Arguments to filter Nodes to count.
   * @example
   * // Count the number of Nodes
   * const count = await prisma.node.count({
   *   where: {
   *     // ... the filter for the Nodes we want to count
   *   }
   * })
  **/
  count<T extends NodeCountArgs>(
    args?: Prisma.Subset<T, NodeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], NodeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Node.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NodeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends NodeAggregateArgs>(args: Prisma.Subset<T, NodeAggregateArgs>): Prisma.PrismaPromise<GetNodeAggregateType<T>>

  /**
   * Group by Node.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NodeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends NodeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: NodeGroupByArgs['orderBy'] }
      : { orderBy?: NodeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, NodeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetNodeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Node model
 */
readonly fields: NodeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Node.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__NodeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  ProductsAsCategory<T extends Prisma.Node$ProductsAsCategoryArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Node$ProductsAsCategoryArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  VariantAsUnit<T extends Prisma.Node$VariantAsUnitArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Node$VariantAsUnitArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VariantPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  ProductsAsBrand<T extends Prisma.Node$ProductsAsBrandArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Node$ProductsAsBrandArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  ProductsAsGst<T extends Prisma.Node$ProductsAsGstArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Node$ProductsAsGstArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  parent<T extends Prisma.Node$parentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Node$parentArgs<ExtArgs>>): Prisma.Prisma__NodeClient<runtime.Types.Result.GetResult<Prisma.$NodePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  children<T extends Prisma.Node$childrenArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Node$childrenArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NodePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  products<T extends Prisma.Node$productsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Node$productsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  variants<T extends Prisma.Node$variantsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Node$variantsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VariantPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Node model
 */
export interface NodeFieldRefs {
  readonly id: Prisma.FieldRef<"Node", 'String'>
  readonly name: Prisma.FieldRef<"Node", 'String'>
  readonly parentId: Prisma.FieldRef<"Node", 'String'>
  readonly type: Prisma.FieldRef<"Node", 'NodeType'>
  readonly value: Prisma.FieldRef<"Node", 'Int'>
}
    

// Custom InputTypes
/**
 * Node findUnique
 */
export type NodeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Node
   */
  select?: Prisma.NodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Node
   */
  omit?: Prisma.NodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NodeInclude<ExtArgs> | null
  /**
   * Filter, which Node to fetch.
   */
  where: Prisma.NodeWhereUniqueInput
}

/**
 * Node findUniqueOrThrow
 */
export type NodeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Node
   */
  select?: Prisma.NodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Node
   */
  omit?: Prisma.NodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NodeInclude<ExtArgs> | null
  /**
   * Filter, which Node to fetch.
   */
  where: Prisma.NodeWhereUniqueInput
}

/**
 * Node findFirst
 */
export type NodeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Node
   */
  select?: Prisma.NodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Node
   */
  omit?: Prisma.NodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NodeInclude<ExtArgs> | null
  /**
   * Filter, which Node to fetch.
   */
  where?: Prisma.NodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Nodes to fetch.
   */
  orderBy?: Prisma.NodeOrderByWithRelationInput | Prisma.NodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Nodes.
   */
  cursor?: Prisma.NodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Nodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Nodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Nodes.
   */
  distinct?: Prisma.NodeScalarFieldEnum | Prisma.NodeScalarFieldEnum[]
}

/**
 * Node findFirstOrThrow
 */
export type NodeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Node
   */
  select?: Prisma.NodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Node
   */
  omit?: Prisma.NodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NodeInclude<ExtArgs> | null
  /**
   * Filter, which Node to fetch.
   */
  where?: Prisma.NodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Nodes to fetch.
   */
  orderBy?: Prisma.NodeOrderByWithRelationInput | Prisma.NodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Nodes.
   */
  cursor?: Prisma.NodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Nodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Nodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Nodes.
   */
  distinct?: Prisma.NodeScalarFieldEnum | Prisma.NodeScalarFieldEnum[]
}

/**
 * Node findMany
 */
export type NodeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Node
   */
  select?: Prisma.NodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Node
   */
  omit?: Prisma.NodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NodeInclude<ExtArgs> | null
  /**
   * Filter, which Nodes to fetch.
   */
  where?: Prisma.NodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Nodes to fetch.
   */
  orderBy?: Prisma.NodeOrderByWithRelationInput | Prisma.NodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Nodes.
   */
  cursor?: Prisma.NodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Nodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Nodes.
   */
  skip?: number
  distinct?: Prisma.NodeScalarFieldEnum | Prisma.NodeScalarFieldEnum[]
}

/**
 * Node create
 */
export type NodeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Node
   */
  select?: Prisma.NodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Node
   */
  omit?: Prisma.NodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NodeInclude<ExtArgs> | null
  /**
   * The data needed to create a Node.
   */
  data: Prisma.XOR<Prisma.NodeCreateInput, Prisma.NodeUncheckedCreateInput>
}

/**
 * Node createMany
 */
export type NodeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Nodes.
   */
  data: Prisma.NodeCreateManyInput | Prisma.NodeCreateManyInput[]
}

/**
 * Node update
 */
export type NodeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Node
   */
  select?: Prisma.NodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Node
   */
  omit?: Prisma.NodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NodeInclude<ExtArgs> | null
  /**
   * The data needed to update a Node.
   */
  data: Prisma.XOR<Prisma.NodeUpdateInput, Prisma.NodeUncheckedUpdateInput>
  /**
   * Choose, which Node to update.
   */
  where: Prisma.NodeWhereUniqueInput
}

/**
 * Node updateMany
 */
export type NodeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Nodes.
   */
  data: Prisma.XOR<Prisma.NodeUpdateManyMutationInput, Prisma.NodeUncheckedUpdateManyInput>
  /**
   * Filter which Nodes to update
   */
  where?: Prisma.NodeWhereInput
  /**
   * Limit how many Nodes to update.
   */
  limit?: number
}

/**
 * Node upsert
 */
export type NodeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Node
   */
  select?: Prisma.NodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Node
   */
  omit?: Prisma.NodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NodeInclude<ExtArgs> | null
  /**
   * The filter to search for the Node to update in case it exists.
   */
  where: Prisma.NodeWhereUniqueInput
  /**
   * In case the Node found by the `where` argument doesn't exist, create a new Node with this data.
   */
  create: Prisma.XOR<Prisma.NodeCreateInput, Prisma.NodeUncheckedCreateInput>
  /**
   * In case the Node was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.NodeUpdateInput, Prisma.NodeUncheckedUpdateInput>
}

/**
 * Node delete
 */
export type NodeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Node
   */
  select?: Prisma.NodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Node
   */
  omit?: Prisma.NodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NodeInclude<ExtArgs> | null
  /**
   * Filter which Node to delete.
   */
  where: Prisma.NodeWhereUniqueInput
}

/**
 * Node deleteMany
 */
export type NodeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Nodes to delete
   */
  where?: Prisma.NodeWhereInput
  /**
   * Limit how many Nodes to delete.
   */
  limit?: number
}

/**
 * Node findRaw
 */
export type NodeFindRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The query predicate filter. If unspecified, then all documents in the collection will match the predicate. ${@link https://docs.mongodb.com/manual/reference/operator/query MongoDB Docs}.
   */
  filter?: runtime.InputJsonValue
  /**
   * Additional options to pass to the `find` command ${@link https://docs.mongodb.com/manual/reference/command/find/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * Node aggregateRaw
 */
export type NodeAggregateRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * An array of aggregation stages to process and transform the document stream via the aggregation pipeline. ${@link https://docs.mongodb.com/manual/reference/operator/aggregation-pipeline MongoDB Docs}.
   */
  pipeline?: runtime.InputJsonValue[]
  /**
   * Additional options to pass to the `aggregate` command ${@link https://docs.mongodb.com/manual/reference/command/aggregate/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * Node.ProductsAsCategory
 */
export type Node$ProductsAsCategoryArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Product
   */
  select?: Prisma.ProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Product
   */
  omit?: Prisma.ProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductInclude<ExtArgs> | null
  where?: Prisma.ProductWhereInput
  orderBy?: Prisma.ProductOrderByWithRelationInput | Prisma.ProductOrderByWithRelationInput[]
  cursor?: Prisma.ProductWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProductScalarFieldEnum | Prisma.ProductScalarFieldEnum[]
}

/**
 * Node.VariantAsUnit
 */
export type Node$VariantAsUnitArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Variant
   */
  select?: Prisma.VariantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Variant
   */
  omit?: Prisma.VariantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VariantInclude<ExtArgs> | null
  where?: Prisma.VariantWhereInput
  orderBy?: Prisma.VariantOrderByWithRelationInput | Prisma.VariantOrderByWithRelationInput[]
  cursor?: Prisma.VariantWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.VariantScalarFieldEnum | Prisma.VariantScalarFieldEnum[]
}

/**
 * Node.ProductsAsBrand
 */
export type Node$ProductsAsBrandArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Product
   */
  select?: Prisma.ProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Product
   */
  omit?: Prisma.ProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductInclude<ExtArgs> | null
  where?: Prisma.ProductWhereInput
  orderBy?: Prisma.ProductOrderByWithRelationInput | Prisma.ProductOrderByWithRelationInput[]
  cursor?: Prisma.ProductWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProductScalarFieldEnum | Prisma.ProductScalarFieldEnum[]
}

/**
 * Node.ProductsAsGst
 */
export type Node$ProductsAsGstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Product
   */
  select?: Prisma.ProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Product
   */
  omit?: Prisma.ProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductInclude<ExtArgs> | null
  where?: Prisma.ProductWhereInput
  orderBy?: Prisma.ProductOrderByWithRelationInput | Prisma.ProductOrderByWithRelationInput[]
  cursor?: Prisma.ProductWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProductScalarFieldEnum | Prisma.ProductScalarFieldEnum[]
}

/**
 * Node.parent
 */
export type Node$parentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Node
   */
  select?: Prisma.NodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Node
   */
  omit?: Prisma.NodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NodeInclude<ExtArgs> | null
  where?: Prisma.NodeWhereInput
}

/**
 * Node.children
 */
export type Node$childrenArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Node
   */
  select?: Prisma.NodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Node
   */
  omit?: Prisma.NodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NodeInclude<ExtArgs> | null
  where?: Prisma.NodeWhereInput
  orderBy?: Prisma.NodeOrderByWithRelationInput | Prisma.NodeOrderByWithRelationInput[]
  cursor?: Prisma.NodeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.NodeScalarFieldEnum | Prisma.NodeScalarFieldEnum[]
}

/**
 * Node.products
 */
export type Node$productsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Product
   */
  select?: Prisma.ProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Product
   */
  omit?: Prisma.ProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductInclude<ExtArgs> | null
  where?: Prisma.ProductWhereInput
  orderBy?: Prisma.ProductOrderByWithRelationInput | Prisma.ProductOrderByWithRelationInput[]
  cursor?: Prisma.ProductWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProductScalarFieldEnum | Prisma.ProductScalarFieldEnum[]
}

/**
 * Node.variants
 */
export type Node$variantsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Variant
   */
  select?: Prisma.VariantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Variant
   */
  omit?: Prisma.VariantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VariantInclude<ExtArgs> | null
  where?: Prisma.VariantWhereInput
  orderBy?: Prisma.VariantOrderByWithRelationInput | Prisma.VariantOrderByWithRelationInput[]
  cursor?: Prisma.VariantWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.VariantScalarFieldEnum | Prisma.VariantScalarFieldEnum[]
}

/**
 * Node without action
 */
export type NodeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Node
   */
  select?: Prisma.NodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Node
   */
  omit?: Prisma.NodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NodeInclude<ExtArgs> | null
}
