
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PromotionType` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model PromotionType
 * 
 */
export type PromotionTypeModel = runtime.Types.Result.DefaultSelection<Prisma.$PromotionTypePayload>

export type AggregatePromotionType = {
  _count: PromotionTypeCountAggregateOutputType | null
  _avg: PromotionTypeAvgAggregateOutputType | null
  _sum: PromotionTypeSumAggregateOutputType | null
  _min: PromotionTypeMinAggregateOutputType | null
  _max: PromotionTypeMaxAggregateOutputType | null
}

export type PromotionTypeAvgAggregateOutputType = {
  value: number | null
  maxDistance: number | null
  minQuantity: number | null
}

export type PromotionTypeSumAggregateOutputType = {
  value: number | null
  maxDistance: number | null
  minQuantity: number | null
}

export type PromotionTypeMinAggregateOutputType = {
  id: string | null
  code: string | null
  value: number | null
  maxDistance: number | null
  minQuantity: number | null
}

export type PromotionTypeMaxAggregateOutputType = {
  id: string | null
  code: string | null
  value: number | null
  maxDistance: number | null
  minQuantity: number | null
}

export type PromotionTypeCountAggregateOutputType = {
  id: number
  code: number
  value: number
  maxDistance: number
  minQuantity: number
  _all: number
}


export type PromotionTypeAvgAggregateInputType = {
  value?: true
  maxDistance?: true
  minQuantity?: true
}

export type PromotionTypeSumAggregateInputType = {
  value?: true
  maxDistance?: true
  minQuantity?: true
}

export type PromotionTypeMinAggregateInputType = {
  id?: true
  code?: true
  value?: true
  maxDistance?: true
  minQuantity?: true
}

export type PromotionTypeMaxAggregateInputType = {
  id?: true
  code?: true
  value?: true
  maxDistance?: true
  minQuantity?: true
}

export type PromotionTypeCountAggregateInputType = {
  id?: true
  code?: true
  value?: true
  maxDistance?: true
  minQuantity?: true
  _all?: true
}

export type PromotionTypeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PromotionType to aggregate.
   */
  where?: Prisma.PromotionTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PromotionTypes to fetch.
   */
  orderBy?: Prisma.PromotionTypeOrderByWithRelationInput | Prisma.PromotionTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PromotionTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PromotionTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PromotionTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PromotionTypes
  **/
  _count?: true | PromotionTypeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PromotionTypeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PromotionTypeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PromotionTypeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PromotionTypeMaxAggregateInputType
}

export type GetPromotionTypeAggregateType<T extends PromotionTypeAggregateArgs> = {
      [P in keyof T & keyof AggregatePromotionType]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePromotionType[P]>
    : Prisma.GetScalarType<T[P], AggregatePromotionType[P]>
}




export type PromotionTypeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PromotionTypeWhereInput
  orderBy?: Prisma.PromotionTypeOrderByWithAggregationInput | Prisma.PromotionTypeOrderByWithAggregationInput[]
  by: Prisma.PromotionTypeScalarFieldEnum[] | Prisma.PromotionTypeScalarFieldEnum
  having?: Prisma.PromotionTypeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PromotionTypeCountAggregateInputType | true
  _avg?: PromotionTypeAvgAggregateInputType
  _sum?: PromotionTypeSumAggregateInputType
  _min?: PromotionTypeMinAggregateInputType
  _max?: PromotionTypeMaxAggregateInputType
}

export type PromotionTypeGroupByOutputType = {
  id: string
  code: string
  value: number
  maxDistance: number | null
  minQuantity: number | null
  _count: PromotionTypeCountAggregateOutputType | null
  _avg: PromotionTypeAvgAggregateOutputType | null
  _sum: PromotionTypeSumAggregateOutputType | null
  _min: PromotionTypeMinAggregateOutputType | null
  _max: PromotionTypeMaxAggregateOutputType | null
}

type GetPromotionTypeGroupByPayload<T extends PromotionTypeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PromotionTypeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PromotionTypeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PromotionTypeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PromotionTypeGroupByOutputType[P]>
      }
    >
  >



export type PromotionTypeWhereInput = {
  AND?: Prisma.PromotionTypeWhereInput | Prisma.PromotionTypeWhereInput[]
  OR?: Prisma.PromotionTypeWhereInput[]
  NOT?: Prisma.PromotionTypeWhereInput | Prisma.PromotionTypeWhereInput[]
  id?: Prisma.StringFilter<"PromotionType"> | string
  code?: Prisma.StringFilter<"PromotionType"> | string
  value?: Prisma.FloatFilter<"PromotionType"> | number
  maxDistance?: Prisma.FloatNullableFilter<"PromotionType"> | number | null
  minQuantity?: Prisma.IntNullableFilter<"PromotionType"> | number | null
  promotions?: Prisma.PromotionListRelationFilter
}

export type PromotionTypeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  value?: Prisma.SortOrder
  maxDistance?: Prisma.SortOrder
  minQuantity?: Prisma.SortOrder
  promotions?: Prisma.PromotionOrderByRelationAggregateInput
}

export type PromotionTypeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  code?: string
  AND?: Prisma.PromotionTypeWhereInput | Prisma.PromotionTypeWhereInput[]
  OR?: Prisma.PromotionTypeWhereInput[]
  NOT?: Prisma.PromotionTypeWhereInput | Prisma.PromotionTypeWhereInput[]
  value?: Prisma.FloatFilter<"PromotionType"> | number
  maxDistance?: Prisma.FloatNullableFilter<"PromotionType"> | number | null
  minQuantity?: Prisma.IntNullableFilter<"PromotionType"> | number | null
  promotions?: Prisma.PromotionListRelationFilter
}, "id" | "code">

export type PromotionTypeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  value?: Prisma.SortOrder
  maxDistance?: Prisma.SortOrder
  minQuantity?: Prisma.SortOrder
  _count?: Prisma.PromotionTypeCountOrderByAggregateInput
  _avg?: Prisma.PromotionTypeAvgOrderByAggregateInput
  _max?: Prisma.PromotionTypeMaxOrderByAggregateInput
  _min?: Prisma.PromotionTypeMinOrderByAggregateInput
  _sum?: Prisma.PromotionTypeSumOrderByAggregateInput
}

export type PromotionTypeScalarWhereWithAggregatesInput = {
  AND?: Prisma.PromotionTypeScalarWhereWithAggregatesInput | Prisma.PromotionTypeScalarWhereWithAggregatesInput[]
  OR?: Prisma.PromotionTypeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PromotionTypeScalarWhereWithAggregatesInput | Prisma.PromotionTypeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PromotionType"> | string
  code?: Prisma.StringWithAggregatesFilter<"PromotionType"> | string
  value?: Prisma.FloatWithAggregatesFilter<"PromotionType"> | number
  maxDistance?: Prisma.FloatNullableWithAggregatesFilter<"PromotionType"> | number | null
  minQuantity?: Prisma.IntNullableWithAggregatesFilter<"PromotionType"> | number | null
}

export type PromotionTypeCreateInput = {
  id?: string
  code: string
  value: number
  maxDistance?: number | null
  minQuantity?: number | null
  promotions?: Prisma.PromotionCreateNestedManyWithoutPromotionTypeInput
}

export type PromotionTypeUncheckedCreateInput = {
  id?: string
  code: string
  value: number
  maxDistance?: number | null
  minQuantity?: number | null
  promotions?: Prisma.PromotionUncheckedCreateNestedManyWithoutPromotionTypeInput
}

export type PromotionTypeUpdateInput = {
  code?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.FloatFieldUpdateOperationsInput | number
  maxDistance?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  minQuantity?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  promotions?: Prisma.PromotionUpdateManyWithoutPromotionTypeNestedInput
}

export type PromotionTypeUncheckedUpdateInput = {
  code?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.FloatFieldUpdateOperationsInput | number
  maxDistance?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  minQuantity?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  promotions?: Prisma.PromotionUncheckedUpdateManyWithoutPromotionTypeNestedInput
}

export type PromotionTypeCreateManyInput = {
  id?: string
  code: string
  value: number
  maxDistance?: number | null
  minQuantity?: number | null
}

export type PromotionTypeUpdateManyMutationInput = {
  code?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.FloatFieldUpdateOperationsInput | number
  maxDistance?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  minQuantity?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type PromotionTypeUncheckedUpdateManyInput = {
  code?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.FloatFieldUpdateOperationsInput | number
  maxDistance?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  minQuantity?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type PromotionTypeScalarRelationFilter = {
  is?: Prisma.PromotionTypeWhereInput
  isNot?: Prisma.PromotionTypeWhereInput
}

export type PromotionTypeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  value?: Prisma.SortOrder
  maxDistance?: Prisma.SortOrder
  minQuantity?: Prisma.SortOrder
}

export type PromotionTypeAvgOrderByAggregateInput = {
  value?: Prisma.SortOrder
  maxDistance?: Prisma.SortOrder
  minQuantity?: Prisma.SortOrder
}

export type PromotionTypeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  value?: Prisma.SortOrder
  maxDistance?: Prisma.SortOrder
  minQuantity?: Prisma.SortOrder
}

export type PromotionTypeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  value?: Prisma.SortOrder
  maxDistance?: Prisma.SortOrder
  minQuantity?: Prisma.SortOrder
}

export type PromotionTypeSumOrderByAggregateInput = {
  value?: Prisma.SortOrder
  maxDistance?: Prisma.SortOrder
  minQuantity?: Prisma.SortOrder
}

export type PromotionTypeCreateNestedOneWithoutPromotionsInput = {
  create?: Prisma.XOR<Prisma.PromotionTypeCreateWithoutPromotionsInput, Prisma.PromotionTypeUncheckedCreateWithoutPromotionsInput>
  connectOrCreate?: Prisma.PromotionTypeCreateOrConnectWithoutPromotionsInput
  connect?: Prisma.PromotionTypeWhereUniqueInput
}

export type PromotionTypeUpdateOneRequiredWithoutPromotionsNestedInput = {
  create?: Prisma.XOR<Prisma.PromotionTypeCreateWithoutPromotionsInput, Prisma.PromotionTypeUncheckedCreateWithoutPromotionsInput>
  connectOrCreate?: Prisma.PromotionTypeCreateOrConnectWithoutPromotionsInput
  upsert?: Prisma.PromotionTypeUpsertWithoutPromotionsInput
  connect?: Prisma.PromotionTypeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PromotionTypeUpdateToOneWithWhereWithoutPromotionsInput, Prisma.PromotionTypeUpdateWithoutPromotionsInput>, Prisma.PromotionTypeUncheckedUpdateWithoutPromotionsInput>
}

export type NullableFloatFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
  unset?: boolean
}

export type PromotionTypeCreateWithoutPromotionsInput = {
  id?: string
  code: string
  value: number
  maxDistance?: number | null
  minQuantity?: number | null
}

export type PromotionTypeUncheckedCreateWithoutPromotionsInput = {
  id?: string
  code: string
  value: number
  maxDistance?: number | null
  minQuantity?: number | null
}

export type PromotionTypeCreateOrConnectWithoutPromotionsInput = {
  where: Prisma.PromotionTypeWhereUniqueInput
  create: Prisma.XOR<Prisma.PromotionTypeCreateWithoutPromotionsInput, Prisma.PromotionTypeUncheckedCreateWithoutPromotionsInput>
}

export type PromotionTypeUpsertWithoutPromotionsInput = {
  update: Prisma.XOR<Prisma.PromotionTypeUpdateWithoutPromotionsInput, Prisma.PromotionTypeUncheckedUpdateWithoutPromotionsInput>
  create: Prisma.XOR<Prisma.PromotionTypeCreateWithoutPromotionsInput, Prisma.PromotionTypeUncheckedCreateWithoutPromotionsInput>
  where?: Prisma.PromotionTypeWhereInput
}

export type PromotionTypeUpdateToOneWithWhereWithoutPromotionsInput = {
  where?: Prisma.PromotionTypeWhereInput
  data: Prisma.XOR<Prisma.PromotionTypeUpdateWithoutPromotionsInput, Prisma.PromotionTypeUncheckedUpdateWithoutPromotionsInput>
}

export type PromotionTypeUpdateWithoutPromotionsInput = {
  code?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.FloatFieldUpdateOperationsInput | number
  maxDistance?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  minQuantity?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type PromotionTypeUncheckedUpdateWithoutPromotionsInput = {
  code?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.FloatFieldUpdateOperationsInput | number
  maxDistance?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  minQuantity?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}


/**
 * Count Type PromotionTypeCountOutputType
 */

export type PromotionTypeCountOutputType = {
  promotions: number
}

export type PromotionTypeCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  promotions?: boolean | PromotionTypeCountOutputTypeCountPromotionsArgs
}

/**
 * PromotionTypeCountOutputType without action
 */
export type PromotionTypeCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromotionTypeCountOutputType
   */
  select?: Prisma.PromotionTypeCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PromotionTypeCountOutputType without action
 */
export type PromotionTypeCountOutputTypeCountPromotionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PromotionWhereInput
}


export type PromotionTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  code?: boolean
  value?: boolean
  maxDistance?: boolean
  minQuantity?: boolean
  promotions?: boolean | Prisma.PromotionType$promotionsArgs<ExtArgs>
  _count?: boolean | Prisma.PromotionTypeCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["promotionType"]>



export type PromotionTypeSelectScalar = {
  id?: boolean
  code?: boolean
  value?: boolean
  maxDistance?: boolean
  minQuantity?: boolean
}

export type PromotionTypeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "code" | "value" | "maxDistance" | "minQuantity", ExtArgs["result"]["promotionType"]>
export type PromotionTypeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  promotions?: boolean | Prisma.PromotionType$promotionsArgs<ExtArgs>
  _count?: boolean | Prisma.PromotionTypeCountOutputTypeDefaultArgs<ExtArgs>
}

export type $PromotionTypePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PromotionType"
  objects: {
    promotions: Prisma.$PromotionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    code: string
    value: number
    maxDistance: number | null
    minQuantity: number | null
  }, ExtArgs["result"]["promotionType"]>
  composites: {}
}

export type PromotionTypeGetPayload<S extends boolean | null | undefined | PromotionTypeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PromotionTypePayload, S>

export type PromotionTypeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PromotionTypeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PromotionTypeCountAggregateInputType | true
  }

export interface PromotionTypeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PromotionType'], meta: { name: 'PromotionType' } }
  /**
   * Find zero or one PromotionType that matches the filter.
   * @param {PromotionTypeFindUniqueArgs} args - Arguments to find a PromotionType
   * @example
   * // Get one PromotionType
   * const promotionType = await prisma.promotionType.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PromotionTypeFindUniqueArgs>(args: Prisma.SelectSubset<T, PromotionTypeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PromotionTypeClient<runtime.Types.Result.GetResult<Prisma.$PromotionTypePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PromotionType that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PromotionTypeFindUniqueOrThrowArgs} args - Arguments to find a PromotionType
   * @example
   * // Get one PromotionType
   * const promotionType = await prisma.promotionType.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PromotionTypeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PromotionTypeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PromotionTypeClient<runtime.Types.Result.GetResult<Prisma.$PromotionTypePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PromotionType that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PromotionTypeFindFirstArgs} args - Arguments to find a PromotionType
   * @example
   * // Get one PromotionType
   * const promotionType = await prisma.promotionType.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PromotionTypeFindFirstArgs>(args?: Prisma.SelectSubset<T, PromotionTypeFindFirstArgs<ExtArgs>>): Prisma.Prisma__PromotionTypeClient<runtime.Types.Result.GetResult<Prisma.$PromotionTypePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PromotionType that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PromotionTypeFindFirstOrThrowArgs} args - Arguments to find a PromotionType
   * @example
   * // Get one PromotionType
   * const promotionType = await prisma.promotionType.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PromotionTypeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PromotionTypeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PromotionTypeClient<runtime.Types.Result.GetResult<Prisma.$PromotionTypePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PromotionTypes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PromotionTypeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PromotionTypes
   * const promotionTypes = await prisma.promotionType.findMany()
   * 
   * // Get first 10 PromotionTypes
   * const promotionTypes = await prisma.promotionType.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const promotionTypeWithIdOnly = await prisma.promotionType.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PromotionTypeFindManyArgs>(args?: Prisma.SelectSubset<T, PromotionTypeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PromotionTypePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PromotionType.
   * @param {PromotionTypeCreateArgs} args - Arguments to create a PromotionType.
   * @example
   * // Create one PromotionType
   * const PromotionType = await prisma.promotionType.create({
   *   data: {
   *     // ... data to create a PromotionType
   *   }
   * })
   * 
   */
  create<T extends PromotionTypeCreateArgs>(args: Prisma.SelectSubset<T, PromotionTypeCreateArgs<ExtArgs>>): Prisma.Prisma__PromotionTypeClient<runtime.Types.Result.GetResult<Prisma.$PromotionTypePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PromotionTypes.
   * @param {PromotionTypeCreateManyArgs} args - Arguments to create many PromotionTypes.
   * @example
   * // Create many PromotionTypes
   * const promotionType = await prisma.promotionType.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PromotionTypeCreateManyArgs>(args?: Prisma.SelectSubset<T, PromotionTypeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a PromotionType.
   * @param {PromotionTypeDeleteArgs} args - Arguments to delete one PromotionType.
   * @example
   * // Delete one PromotionType
   * const PromotionType = await prisma.promotionType.delete({
   *   where: {
   *     // ... filter to delete one PromotionType
   *   }
   * })
   * 
   */
  delete<T extends PromotionTypeDeleteArgs>(args: Prisma.SelectSubset<T, PromotionTypeDeleteArgs<ExtArgs>>): Prisma.Prisma__PromotionTypeClient<runtime.Types.Result.GetResult<Prisma.$PromotionTypePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PromotionType.
   * @param {PromotionTypeUpdateArgs} args - Arguments to update one PromotionType.
   * @example
   * // Update one PromotionType
   * const promotionType = await prisma.promotionType.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PromotionTypeUpdateArgs>(args: Prisma.SelectSubset<T, PromotionTypeUpdateArgs<ExtArgs>>): Prisma.Prisma__PromotionTypeClient<runtime.Types.Result.GetResult<Prisma.$PromotionTypePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PromotionTypes.
   * @param {PromotionTypeDeleteManyArgs} args - Arguments to filter PromotionTypes to delete.
   * @example
   * // Delete a few PromotionTypes
   * const { count } = await prisma.promotionType.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PromotionTypeDeleteManyArgs>(args?: Prisma.SelectSubset<T, PromotionTypeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PromotionTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PromotionTypeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PromotionTypes
   * const promotionType = await prisma.promotionType.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PromotionTypeUpdateManyArgs>(args: Prisma.SelectSubset<T, PromotionTypeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one PromotionType.
   * @param {PromotionTypeUpsertArgs} args - Arguments to update or create a PromotionType.
   * @example
   * // Update or create a PromotionType
   * const promotionType = await prisma.promotionType.upsert({
   *   create: {
   *     // ... data to create a PromotionType
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PromotionType we want to update
   *   }
   * })
   */
  upsert<T extends PromotionTypeUpsertArgs>(args: Prisma.SelectSubset<T, PromotionTypeUpsertArgs<ExtArgs>>): Prisma.Prisma__PromotionTypeClient<runtime.Types.Result.GetResult<Prisma.$PromotionTypePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PromotionTypes that matches the filter.
   * @param {PromotionTypeFindRawArgs} args - Select which filters you would like to apply.
   * @example
   * const promotionType = await prisma.promotionType.findRaw({
   *   filter: { age: { $gt: 25 } }
   * })
   */
  findRaw(args?: Prisma.PromotionTypeFindRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>

  /**
   * Perform aggregation operations on a PromotionType.
   * @param {PromotionTypeAggregateRawArgs} args - Select which aggregations you would like to apply.
   * @example
   * const promotionType = await prisma.promotionType.aggregateRaw({
   *   pipeline: [
   *     { $match: { status: "registered" } },
   *     { $group: { _id: "$country", total: { $sum: 1 } } }
   *   ]
   * })
   */
  aggregateRaw(args?: Prisma.PromotionTypeAggregateRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>


  /**
   * Count the number of PromotionTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PromotionTypeCountArgs} args - Arguments to filter PromotionTypes to count.
   * @example
   * // Count the number of PromotionTypes
   * const count = await prisma.promotionType.count({
   *   where: {
   *     // ... the filter for the PromotionTypes we want to count
   *   }
   * })
  **/
  count<T extends PromotionTypeCountArgs>(
    args?: Prisma.Subset<T, PromotionTypeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PromotionTypeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PromotionType.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PromotionTypeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PromotionTypeAggregateArgs>(args: Prisma.Subset<T, PromotionTypeAggregateArgs>): Prisma.PrismaPromise<GetPromotionTypeAggregateType<T>>

  /**
   * Group by PromotionType.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PromotionTypeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PromotionTypeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PromotionTypeGroupByArgs['orderBy'] }
      : { orderBy?: PromotionTypeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PromotionTypeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPromotionTypeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PromotionType model
 */
readonly fields: PromotionTypeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PromotionType.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PromotionTypeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  promotions<T extends Prisma.PromotionType$promotionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PromotionType$promotionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PromotionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PromotionType model
 */
export interface PromotionTypeFieldRefs {
  readonly id: Prisma.FieldRef<"PromotionType", 'String'>
  readonly code: Prisma.FieldRef<"PromotionType", 'String'>
  readonly value: Prisma.FieldRef<"PromotionType", 'Float'>
  readonly maxDistance: Prisma.FieldRef<"PromotionType", 'Float'>
  readonly minQuantity: Prisma.FieldRef<"PromotionType", 'Int'>
}
    

// Custom InputTypes
/**
 * PromotionType findUnique
 */
export type PromotionTypeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromotionType
   */
  select?: Prisma.PromotionTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromotionType
   */
  omit?: Prisma.PromotionTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromotionTypeInclude<ExtArgs> | null
  /**
   * Filter, which PromotionType to fetch.
   */
  where: Prisma.PromotionTypeWhereUniqueInput
}

/**
 * PromotionType findUniqueOrThrow
 */
export type PromotionTypeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromotionType
   */
  select?: Prisma.PromotionTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromotionType
   */
  omit?: Prisma.PromotionTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromotionTypeInclude<ExtArgs> | null
  /**
   * Filter, which PromotionType to fetch.
   */
  where: Prisma.PromotionTypeWhereUniqueInput
}

/**
 * PromotionType findFirst
 */
export type PromotionTypeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromotionType
   */
  select?: Prisma.PromotionTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromotionType
   */
  omit?: Prisma.PromotionTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromotionTypeInclude<ExtArgs> | null
  /**
   * Filter, which PromotionType to fetch.
   */
  where?: Prisma.PromotionTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PromotionTypes to fetch.
   */
  orderBy?: Prisma.PromotionTypeOrderByWithRelationInput | Prisma.PromotionTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PromotionTypes.
   */
  cursor?: Prisma.PromotionTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PromotionTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PromotionTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PromotionTypes.
   */
  distinct?: Prisma.PromotionTypeScalarFieldEnum | Prisma.PromotionTypeScalarFieldEnum[]
}

/**
 * PromotionType findFirstOrThrow
 */
export type PromotionTypeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromotionType
   */
  select?: Prisma.PromotionTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromotionType
   */
  omit?: Prisma.PromotionTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromotionTypeInclude<ExtArgs> | null
  /**
   * Filter, which PromotionType to fetch.
   */
  where?: Prisma.PromotionTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PromotionTypes to fetch.
   */
  orderBy?: Prisma.PromotionTypeOrderByWithRelationInput | Prisma.PromotionTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PromotionTypes.
   */
  cursor?: Prisma.PromotionTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PromotionTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PromotionTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PromotionTypes.
   */
  distinct?: Prisma.PromotionTypeScalarFieldEnum | Prisma.PromotionTypeScalarFieldEnum[]
}

/**
 * PromotionType findMany
 */
export type PromotionTypeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromotionType
   */
  select?: Prisma.PromotionTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromotionType
   */
  omit?: Prisma.PromotionTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromotionTypeInclude<ExtArgs> | null
  /**
   * Filter, which PromotionTypes to fetch.
   */
  where?: Prisma.PromotionTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PromotionTypes to fetch.
   */
  orderBy?: Prisma.PromotionTypeOrderByWithRelationInput | Prisma.PromotionTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PromotionTypes.
   */
  cursor?: Prisma.PromotionTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PromotionTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PromotionTypes.
   */
  skip?: number
  distinct?: Prisma.PromotionTypeScalarFieldEnum | Prisma.PromotionTypeScalarFieldEnum[]
}

/**
 * PromotionType create
 */
export type PromotionTypeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromotionType
   */
  select?: Prisma.PromotionTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromotionType
   */
  omit?: Prisma.PromotionTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromotionTypeInclude<ExtArgs> | null
  /**
   * The data needed to create a PromotionType.
   */
  data: Prisma.XOR<Prisma.PromotionTypeCreateInput, Prisma.PromotionTypeUncheckedCreateInput>
}

/**
 * PromotionType createMany
 */
export type PromotionTypeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PromotionTypes.
   */
  data: Prisma.PromotionTypeCreateManyInput | Prisma.PromotionTypeCreateManyInput[]
}

/**
 * PromotionType update
 */
export type PromotionTypeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromotionType
   */
  select?: Prisma.PromotionTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromotionType
   */
  omit?: Prisma.PromotionTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromotionTypeInclude<ExtArgs> | null
  /**
   * The data needed to update a PromotionType.
   */
  data: Prisma.XOR<Prisma.PromotionTypeUpdateInput, Prisma.PromotionTypeUncheckedUpdateInput>
  /**
   * Choose, which PromotionType to update.
   */
  where: Prisma.PromotionTypeWhereUniqueInput
}

/**
 * PromotionType updateMany
 */
export type PromotionTypeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PromotionTypes.
   */
  data: Prisma.XOR<Prisma.PromotionTypeUpdateManyMutationInput, Prisma.PromotionTypeUncheckedUpdateManyInput>
  /**
   * Filter which PromotionTypes to update
   */
  where?: Prisma.PromotionTypeWhereInput
  /**
   * Limit how many PromotionTypes to update.
   */
  limit?: number
}

/**
 * PromotionType upsert
 */
export type PromotionTypeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromotionType
   */
  select?: Prisma.PromotionTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromotionType
   */
  omit?: Prisma.PromotionTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromotionTypeInclude<ExtArgs> | null
  /**
   * The filter to search for the PromotionType to update in case it exists.
   */
  where: Prisma.PromotionTypeWhereUniqueInput
  /**
   * In case the PromotionType found by the `where` argument doesn't exist, create a new PromotionType with this data.
   */
  create: Prisma.XOR<Prisma.PromotionTypeCreateInput, Prisma.PromotionTypeUncheckedCreateInput>
  /**
   * In case the PromotionType was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PromotionTypeUpdateInput, Prisma.PromotionTypeUncheckedUpdateInput>
}

/**
 * PromotionType delete
 */
export type PromotionTypeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromotionType
   */
  select?: Prisma.PromotionTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromotionType
   */
  omit?: Prisma.PromotionTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromotionTypeInclude<ExtArgs> | null
  /**
   * Filter which PromotionType to delete.
   */
  where: Prisma.PromotionTypeWhereUniqueInput
}

/**
 * PromotionType deleteMany
 */
export type PromotionTypeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PromotionTypes to delete
   */
  where?: Prisma.PromotionTypeWhereInput
  /**
   * Limit how many PromotionTypes to delete.
   */
  limit?: number
}

/**
 * PromotionType findRaw
 */
export type PromotionTypeFindRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The query predicate filter. If unspecified, then all documents in the collection will match the predicate. ${@link https://docs.mongodb.com/manual/reference/operator/query MongoDB Docs}.
   */
  filter?: runtime.InputJsonValue
  /**
   * Additional options to pass to the `find` command ${@link https://docs.mongodb.com/manual/reference/command/find/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * PromotionType aggregateRaw
 */
export type PromotionTypeAggregateRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * An array of aggregation stages to process and transform the document stream via the aggregation pipeline. ${@link https://docs.mongodb.com/manual/reference/operator/aggregation-pipeline MongoDB Docs}.
   */
  pipeline?: runtime.InputJsonValue[]
  /**
   * Additional options to pass to the `aggregate` command ${@link https://docs.mongodb.com/manual/reference/command/aggregate/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * PromotionType.promotions
 */
export type PromotionType$promotionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Promotion
   */
  select?: Prisma.PromotionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Promotion
   */
  omit?: Prisma.PromotionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromotionInclude<ExtArgs> | null
  where?: Prisma.PromotionWhereInput
  orderBy?: Prisma.PromotionOrderByWithRelationInput | Prisma.PromotionOrderByWithRelationInput[]
  cursor?: Prisma.PromotionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PromotionScalarFieldEnum | Prisma.PromotionScalarFieldEnum[]
}

/**
 * PromotionType without action
 */
export type PromotionTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PromotionType
   */
  select?: Prisma.PromotionTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PromotionType
   */
  omit?: Prisma.PromotionTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromotionTypeInclude<ExtArgs> | null
}
